### ISSUE TITLE
Guides ? broken links ?

### ISSUE THREAD

**Issue by orchid00** [ropensci/dev_guide#103]
when reading this https://ropensci.github.io/dev_guide/policies.html#review-process
see our packaging guide and reviewing guide for more details
have broken links and i am wondering where to find the mentioned guides.

**Comment by maelle** [comment]
Thanks! I've just made a commit to fix this but in the meantime here are the links
https://ropensci.github.io/dev_guide/building.html
https://ropensci.github.io/dev_guide/onboarding-guide-for-reviewers.html

**Comment by orchid00** [comment]
thanks @maelle
but the second links is also broken https://ropensci.github.io/dev_guide/onboarding-guide-for-reviewers.html

**Comment by maelle** [comment]
Oops I changed it in the meantime, how stupid, sorry! https://ropensci.github.io/dev_guide/#reviewerguide
