### ISSUE TITLE
Reviewer guide needs more instructions re Suggests

### ISSUE THREAD

**Issue by cboettig** [ropensci/dev_guide#112]
The guidelines for reviewers should state that reviewers will need to install the review package using `install(dependencies=TRUE)` (or similar command) to install Suggested packages. It seems pretty common for reviewers to report issues like 

```
✖ fix this R CMD check ERROR: Package suggested but not available: ‘spelling’
```

as errors to the package author.  In general, it can be pretty confusing for newer (and not newer) developers that `Suggests` is essentially a list of packages needed for testing, I suppose a more detailed discussion of to use Suggests for (and what not to) might also be warranted?

**Comment by maelle** [comment]
Good catch! Interested in making a PR? :smiley_cat:

**Comment by maelle** [comment]
First part of these suggestions has been implemented.

**Comment by maelle** [comment]
:wave: @cboettig, friendly ping reg the above, what do you think is still missing?
