### ISSUE TITLE
Mention updating the the Airtable database in the Guide for Editors

### ISSUE THREAD

**Issue by annakrystalli** [ropensci/dev_guide#113]
Might be useful to add reminders in the [Guide for Editors](https://ropensci.github.io/dev_guide/editorguide.html) to update the reviewer database with review details as required throughout the review process?

**Comment by maelle** [comment]
Yes! Interested in making a PR?

**Comment by annakrystalli** [comment]
Sure 😉

**Comment by annakrystalli** [comment]
Am about to make a PR for this. Should I make it straight to `master` or would you prefer it to `devel`?
