### ISSUE TITLE
Guidance on when to submit and package stability

### ISSUE THREAD

**Issue by noamross** [ropensci/dev_guide#114]
The guide for authors section should include some language on at what stage of development to submit a package.  Possible things to include:

- Placing in the context of status badges, e.g., at the stage movement from WIP -> Active, or from Experimental -> Maturing.
- Major functions are stable enough to be fully documented and tested.
- Stating that packages continue to develop after review.

**Comment by maelle** [comment]
Interested in making a PR? The last point could include a cross reference to the chapter about package evolution.
