### ISSUE TITLE
Interactive step through of how to contribute?

### ISSUE THREAD

**Issue by sckott** [ropensci/dev_guide#126]
@dsholler pointed out GNOME newcomers guide https://wiki.gnome.org/Newcomers/ and it's a cool way I think to get people familiar by stepping through various parts - it'd have to be on our website or at least not in the book I imagine, but could be useful maybe?

**Comment by maelle** [comment]
Interesting. @stefaniebutland do you happen to have had feedback from potential/new contributors about what was the hardest part of becoing a contributor?

**Comment by stefaniebutland** [comment]
It's probably a bad sign that I have *not* gotten feedback about the hardest part of becoming a contributor.

I do think there is a perception of rOpenSci as an elite group or insiders club, so having a newcomers guide would likely help that

**Comment by maelle** [comment]
Thanks! But what to put in it 🤔

**Comment by stefaniebutland** [comment]
This is def in the community management department :-)
Sounds like a capital P Project, or at least something I'd want to think/talk/work through in collaboration with someone if we decide this is a priority. Might have a better sense after all-hands

**Comment by dsholler** [comment]
I'm happy to chat with anyone about what I've heard from newcomers to OSS projects and to rOpenSci. Some points that have been salient in responses to questions about newcomer contributions, most of which rOpenSci already addresses on its website and repos:

-  _What contributions are welcome?_ Pretty clear for rOpenSci--new packages, editorial volunteering or inquiries, maintenance, etc. But maybe useful to think about future needs and signal them in the newcomer guide
-  _What's in it for me?_ This comes mostly from people who use software but don't contribute back. Maybe rare in the set of people reaching out to rOpenSci about contribution opportunities. The clear categories of rewards here are peer reviewed, citable objects and access to a high-profile network. But other options in the guide might be lower-level things like "I could use feedback on my code/package," and filter the user to appropriate rOpenSci resources for early-stage development.
-  _Desire for clear contribution guidelines_ Newcomers seem to want easy-to-access-and-navigate style guides, standards, required tests, etc. I think rOpenSci already has this covered and could just link to those docs.
-  _Desire to have a "point person" for questions/feedback_ It helps newcomers when they have one or two people they can ask all-purpose questions of--where to go for guidance on a very specific technical issue down to the appropriate way to ask a question on StackOverflow or a Slack channel. Stef has that covered for rOpenSci, but smaller projects might not have that advantage. 
-  _What is the organization's model of mentorship, if any?_ OSS projects can't mentor every contributor. Is mentorship available? If so, what do you have to do to receive mentorship (e.g., get a fellowship/come to an unconf/reach out on your own/any number of others)? 
-  _What are the norms of communication?_ How do I establish first contact (e.g., file an issue, email) - in this case, the first contact might be the Newcomers tool, or the tool might be a second contact point (e.g., after a potential contributor contacts a staff member and is redirected there). What should I expect for turnaround time? Who can I follow up with?

**Comment by noamross** [comment]
This is great feedback, Dan! A couple of thoughts:

- Signing up to be a reviewer is the most straightforward way to join in, but it's a one-way communication - someone who signs up is added to our database but may not get a review assignment soon, or ever.  Perhaps when they fill out the form they could get a message about other ways to contribute?
- It would also be great to have some more regular approach of connecting new users with package maintainers who need help.  Perhaps we could make a page that aggregates issues from across rOpenSci packages, especially `help-wanted` or `good-first-issue` ones?

**Comment by stefaniebutland** [comment]
@dsholler That is SO helpful. I def want to follow up with you (and others might want to join a chat), but likely after all-hands 

@noamross YES to both your comments

**Comment by maelle** [comment]
> Perhaps when they fill out the form they could get a message about other ways to contribute?

@karthik to keep in mind when we update the form.

**Comment by maelle** [comment]
Would a guide for newcomers be a part of the dev_guide or something linked from the dev_guide?

**Comment by stefaniebutland** [comment]
Feels like it would be part of the dev guide since they are intimately linked. But before I typed that I thought they should be separate sooo.... we'll be sure to have a rich discussion when the time comes.

**Comment by noamross** [comment]
I tend to think that they should be more separate, or be a high-level division of a common site, because the paths for contributing are pretty distinct:
- Contributing a package: Go to dev guide
- Be a reviewer: Sign up as a reviewer via a form
- Help with maintenance of an RO package: Check out the aggregated issues list (I still like this idea a lot, and if we made it, could do some outreach to all our authors about tagging issues)

**Comment by stefaniebutland** [comment]
Talked with Karthik about this. In not-too-distant future, our website could provide entry-points for people including the items Noam noted above and linking to/showing help-wanted and good-first-issue issues for example.

**Comment by sckott** [comment]
pushing to next milestone

**Comment by maelle** [comment]
@stefaniebutland should the whole https://devguide.ropensci.org/contributingguide.html be replaced with a link to the contributing guide? Also, maybe the resources listed under "Learning about package development" might find a home in the contributing guide?

**Comment by stefaniebutland** [comment]
https://contributing.ropensci.org/ is coming!

**Comment by maelle** [comment]
I know but I wonder whether the whole chapter https://devguide.ropensci.org/contributingguide.html should be replaced with a link to that, and what the section about learning package development should become (it might be useful in the contributing guide like the resources for git).

**Comment by maelle** [comment]
:wave: @stefaniebutland :slightly_smiling_face:

**Comment by stefaniebutland** [comment]
My [draft pull request](https://github.com/ropensci/dev_guide/pull/280) deleted the section on learning about package development. I propose that that section be moved to Chapter 1 Packaging Guide. a) because the dev guide is specifically about package dev and b) I don't want the Contributing Guide to maintain more than rOpenSci resources themselves and the minimal set of outside resources.
