### ISSUE TITLE
Guidelines on taking over a pkg from another maintainer 

### ISSUE THREAD

**Issue by sckott** [ropensci/dev_guide#128]
sort of related to #127 - we've had a few of these so far, and will likely have these situations moving forward inevitably. 

We should give some guidance on how this works, and what happens in different scenarios.

**Comment by maelle** [comment]
@sckott what exactly do you mean by different scenarios? I'm assuming

- Package not on CRAN yet
- Package on CRAN
- Package archived on CRAN

or do you mean something else?

**Comment by sckott** [comment]
Yeah, and scenarios related to maintainers, e.g.

- current maintainer is completely missing and not responding 

Also, detail that current maintainer needs to contact CRAN and say who the new maintainer is, etc.

Maybe we should also discuss some suggestions for taking over related to the actual code:

- can the new maintainer rip everything out and start new essentially? or should we implore the new mtaintainer to keep some amount of consistency, at least the public API
- any rules about them adding new contribs with admin access?
- anything else?

**Comment by maelle** [comment]
Regarding changing stuff yes keeping the interface.

Somewhere in the guide we ask folks to let us with admin rights to the org invite folks cf https://ropensci.github.io/dev_guide/collaboration.html#welcoming-collaborators-to-ropensci this is IMO independent of maintainer changes.

Would you have time to make a PR? Would this be a new short chapter in the maintenance part?

**Comment by maelle** [comment]
> current maintainer is completely missing and not responding

I think this is our job as editors/staff to handle this, the chapter could be for someone invited to be a new maintainer, but we could tell folks to contact us if they think a package would need a new maintainer and they want to volunteer?

**Comment by sckott** [comment]
i can do a PR but i think you're more familiar with the dev guide, do you think it's a new chapter, or just a short section in an existing chapter?

**Comment by maelle** [comment]
Thanks! I don't see an existing chapter where it would fit and most chapters of that part are short. Maybe between chapters 9 and 10? Or as very last chapter after the one after contributing.

**Comment by maelle** [comment]
No hurry for the PR btw, next week is fine.

I know the dev guide better but you recruited all the new maintainers 😉

**Comment by noamross** [comment]
I think this is a new chapter but it is something that could use extra visibility and feedback, as I don't think it's been summarized/articulated anywhere else.  Why don't we write it as a blog post, see what forum/twitter/etc feedback we get, and then incorporate it into the guide in the next cycle?

**Comment by maelle** [comment]
I like the idea!

**Comment by maelle** [comment]
@sckott would you be up to first-authoring that blog post? It'd be the occasion to highlight your work on recruiting new maintainers.

Also linked to Julia Silge's post to be published today https://deploy-preview-444--ropensci.netlify.com/blog/2019/04/30/qualtrics-relaunch/

**Comment by sckott** [comment]
Sure, can do.

**Comment by maelle** [comment]
Thanks! I added it to the release after the one we're working on, so you can publish that post in the next months and we can add the corresponding content in August (well, _I_ can't add it but I hope someone can; I can help with the post if you start within the next weeks :smile_cat: ).

**Comment by stefaniebutland** [comment]
Dovetails with the concept of a community call on the topic of maintaining a package https://github.com/rosadmin/comms/issues/62

**Comment by maelle** [comment]
blog post https://ropensci.org/blog/2019/06/12/taking-over-maint/

forum thread https://discuss.ropensci.org/t/taking-over-maintenance-of-a-software-package/1738

**Comment by sckott** [comment]
There's a a few bits of feedback here https://discuss.ropensci.org/t/taking-over-maintenance-of-a-software-package/1738 - i'll go ahead and prepare this section and then ask for feedback

**Comment by sckott** [comment]
I've started a chapter for this - see https://github.com/ropensci/dev_guide/blob/taking-maint/maintenance_changing_maintainers.Rmd - should I do a PR for this to see it rendered?

**Comment by maelle** [comment]
Sadly at the moment we do not render PRs, only master and dev. I reckon having PR rendering would be nice, maybe you can open an issue about that and it could be done for  the winter release? Which does not help for this chapter, sorry 😁

**Comment by sckott** [comment]
okay, no worries. will open an issue.

**Comment by cboettig** [comment]
The new section from #194 looks great! :tada:

**Comment by sckott** [comment]
thanks Carl
