### ISSUE TITLE
making a pdf copy available for the book

### ISSUE THREAD

**Issue by IndrajeetPatil** [ropensci/dev_guide#131]
Will it be possible to have a `.pdf` version of this book that I can download from somewhere?

Thanks.

**Comment by maelle** [comment]
:wave: @IndrajeetPatil, thanks for your suggestion! 

I've added a PDF output to the dev version of the `dev_guide` over at https://devdevguide.netlify.com/ It's quite ugly, I'll try to at least add color to the URLs.

For your use case, would you be interested in an EPUB too while we're at it?

**Comment by IndrajeetPatil** [comment]
I personally much prefer a pdf version of the document over epub. This request was inspired by reading the `tidyverse` style guide in pdf format (https://twitter.com/hadleywickham/status/1091774173758795776), which I found to be stylistically very elegant and readable.

**Comment by maelle** [comment]
Oh nice! Well it'd be quite bad if their styleguide was not stylistically very elegant. :grin: 

Are you happy with the current PDF export? Direct link https://devdevguide.netlify.com/ropensci-dev-guide.pdf We'll make it available for the main dev_guide version after the next release in a couple of months.

**Comment by IndrajeetPatil** [comment]
Yes, yes, sorry forgot to mention that. It looks lovely :)

If you want, you can close this thread. I am happy with the current output.

**Comment by maelle** [comment]
Awesome, thanks again for your suggestion and happy reading! Come back to this issue tracker if you get further ideas while reading. :wink:
