### ISSUE TITLE
Guidelines on testing oldrel and devel

### ISSUE THREAD

**Issue by annakrystalli** [ropensci/dev_guide#132]
Currently the CI section lacks guidance on testing on `oldrel` and `devel`. 

- [ ] We agree we should advise people to set up CI on oldrel, release, and devel on linux, just because it’s easy through TRAVIS. 

- [ ] There's also the suggestion to PR this into `usethis::use_travis()`? It's a well-documented example at https://docs.travis-ci.com/user/languages/r/#r-versions.

> when we add something, we should consider whether there is sufficient adoption, examples, tutorials, etc. for barriers to adoption be low.  In some cases we want to set a new standard, but I always try to think about whether it will be a curve ball for some. In this case, yes, mostly fine, but having `usethis` support it would make it a smidgen easier. (edited) 

- [ ] In any case it will be important to provide documentation for startegies on testing and debugging, especially locally.
  - use Rocker Docker images different tags to test the package.
    `docker run -v $(pwd):/pkg rocker/verse:devel Rscript "devtools::check('/pkg')"`
  - stick to always making commits in a dev or feature branch and let TRAVIS do the testing before merging into master.  Simple but can be slow and frustrating to push, find an error, and start again with not that many ways to inspect the issue.

**Comment by maelle** [comment]
@annakrystalli would you have time to make a PR to this guide?

Regarding the helper function, had you talked to `usethis` folks? If they want to keep their helper template simple (which I assume they want), we can add a similar function to [`rodev`](https://github.com/ropenscilabs/rodev).

**Comment by maelle** [comment]
Regarding your last two points,

* `rhub` has helpers for local debugging with Docker but it does not work on Windows yet. https://r-hub.github.io/rhub/articles/local-debugging.html

* The gitflow approach is documented in https://ropensci.github.io/dev_guide/collaboration.html#working-with-collaborators-including-yourself at the moment. Do you want to add more about CI? I guess this sections is quite hidden but adding it to the packaging guide itself (first and second chapters) would not be optimal either given it's already long. :thinking:

**Comment by annakrystalli** [comment]
Sure thing! I might only get round to it this weekend. Is that cool?

**Comment by maelle** [comment]
Yes! :tada:
