### ISSUE TITLE
light blue text in the book is awfully hard to read

### ISSUE THREAD

**Issue by kwstat** [ropensci/dev_guide#138]
See the website for the book here:
[https://ropensci.github.io/dev_guide/building.html](https://ropensci.github.io/dev_guide/building.html)

The text has a lot of links, which currently appear as light blue text on white.  The low contrast of light blue on white is really hard for some of us to read, or in certain lighting conditions.  Please use dark blue links.

**Comment by maelle** [comment]
Thanks for the feedback, and sorry about this!

Does the blue on https://devdevguide.netlify.com/ improve readability? I've used the darkest blue from https://github.com/ropensci/roweb2/blob/master/themes/ropensci/static/css/general.pcss but obviously if it's not enough I'd need to branch out.

By the way do you experience similar issues with links on https://ropensci.org/?

**Comment by maelle** [comment]
Other possible blue, suggested by @jeroen, GitHub's blue for links, #0366d6.

**Comment by kwstat** [comment]
The minimum legibility standard for contrast is 4.5:1.  Nice write-up here:
https://medium.com/@uistephen/text-contrast-for-web-pages-d685636c0749

Here's a tool for checking contrast: http://wave.webaim.org/
To use it: enter a link, then click on the "Contrast" tab in the upper left corner.  Then click on one of the "ABC" icons and in the lower left part of the page is information about the contrast ratio.

The old version of the page (https://ropensci.github.io/dev_guide/building.html) had blue link contrast ratio 2.32:1.
The new version of the page (https://devdevguide.netlify.com/building.html) has a contrast ratio 3.51:1.
The ropensci.org blue text has contrast ratio 2.94:1
The github blue has a contrast ratio of 5.42:1.
Since the recommended minimum is 4.5:1, the github blue would be a good choice.

**Comment by maelle** [comment]
Thanks a ton for all this information!

**Comment by maelle** [comment]
@kwstat now things are much better in https://devdevguide.netlify.com/ We'll release it at the beginning of May cf #140, after that the main dev guide https://ropensci.github.io/dev_guide/building.html will be legible too. Sorry for the inconvenience and thanks again for your feedback and explanations!
