### ISSUE TITLE
Add use of rOpenSci forum to maintenance section

### ISSUE THREAD

**Issue by noamross** [ropensci/dev_guide#141]
Per questions on the Slack, we should recommend that authors make use of another forum, such as the rOpenSci forum for non-issue related discussions, case studies, etc.  This can go in the Maintenance section.  One recommendation could be for this to be part of an issue template, adding text such as "If this is a question, case study, or otherwise not a bug or feature request for the software itself, please use use X for discussion."

**Comment by maelle** [comment]
A problem I have with guidance reg the issue template is that `rodev`, [where such templates would live](https://github.com/ropenscilabs/rodev/) (there is a function for using the rOpenSci issue and PR templates), isn't ready for release. But maybe it's fine at this point to mention the forum, and tell authors to mention it in the docs/issue template as they see fit?
