### ISSUE TITLE
Switch to latest-release Zenodo badge

### ISSUE THREAD

**Issue by noamross** [ropensci/dev_guide#143]
If we use the "umbrella DOI" from Zenodo and associated badge: https://doi.org/10.5281/zenodo.2553043, it will not need to be updated with each new release, but rather will always resolve to the latest release.

```
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.2553043.svg)](https://doi.org/10.5281/zenodo.2553043)
```

**Comment by maelle** [comment]
is the new badge ok? I added a sentence for the PDF output.

**Comment by noamross** [comment]
In a comment on the PR I changed it so the badge itself, not only the link, uses the umbrella DOI

**Comment by maelle** [comment]
thanks!

**Comment by maelle** [comment]
so I think this will have been solved at release when dev is merged into master, thanks a ton.
