### ISSUE TITLE
Add a bit more content to the security chapter

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#154]
At least a link to the comm call. https://ropensci.org/commcalls/2019-05-07/

**Comment by maelle** [comment]
Working even a bit more on this chapter would be a huge gain for the guide.

**Comment by maelle** [comment]
It could be postponed to another release though.

**Comment by maelle** [comment]
Another topic that might be worth discussing in the chapter is how to handle private keys/other credentials (area where @sckott for instance has a lot of expertise :wink:)

* How to protect your users
    * Where to recommend they store the credentials and why
    * Not printing it?
    * In rOpenSci issue template, it's written not to give one's key. If they do tell them.

* As a developer
    * How to share your key with CI systems
    * Consequence of credentials needed for PRs, probably it means some tests have to be skipped, since there's no easy approach https://discuss.ropensci.org/t/github-pat-needed-in-tests-and-pull-requests-on-travis/1550/7

**Comment by sckott** [comment]
Good idea @maelle 

happy to add some info about this. - also should note about testing as well, make sure not to expose credentials in test suites

**Comment by maelle** [comment]
If you can do a PR it'd be grand. The chapter would only have this subsection for now but it is better than nothing, and an important subsection.

**Comment by sckott** [comment]
okay

**Comment by maelle** [comment]
@sckott when you add your subsection make sure to update the summary at the beginning of the chapter ("not fully written" or so) :-)

**Comment by sckott** [comment]
@maelle  

I haven't got around to this yet. right now the chapter looks like:

<img width="851" alt="Screen Shot 2019-09-26 at 12 42 08 PM" src="https://user-images.githubusercontent.com/577668/65719662-1c1fc280-e05b-11e9-8ed6-c532ce736365.png">

Do we want to leave that as is? Or leave it out of this next version?

**Comment by maelle** [comment]
Please leave it as is, it can improve in the next milestone and the links are better than nothing 🙂

**Comment by sckott** [comment]
sounds good, thanks

**Comment by maelle** [comment]
Fixed in #237
