### ISSUE TITLE
Dashboard on front page

### ISSUE THREAD

**Issue by noamross** [ropensci/dev_guide#16]
If this dev guide is to be a "landing page" for onboarding, its first chapter could include a live dashboard of issues, using JS to pull the status of issues from GH.

It's possible there should be a separate landing page which has just a few links to the book, the main repo issues, and maybe the sign up link, and maybe our packages page.

**Comment by maelle** [comment]
> It's possible there should be a separate landing page which has just a few links to the book, the main repo issues, and maybe the sign up link, and maybe our packages page.

Yes, am going to open an issue in the website repo.
