### ISSUE TITLE
Add guidance about GitHub language detection

### ISSUE THREAD

**Issue by Bisaloo** [ropensci/dev_guide#171]
Feel free to move this issue if you think it belongs to another repo but I think it would make a worthwhile addition to the [grooming section](https://ropensci.github.io/dev_guide/grooming.html).

Some packages (including rOpenSci packages such as [`skimr`](https://github.com/ropensci/skimr), [`rsnps`](https://github.com/ropensci/rsnps) or [`rdflib`](https://github.com/ropensci/rdflib)) are mistakenly classified as `HTML` repos by GitHub. This hinders discoverability as they cannot be found in a search with the `language: r` filter.

It would be very useful to add pointers about how people can mitigate this issue (e.g. https://github.com/github/linguist#overrides).

**Comment by Bisaloo** [comment]
Closing as this is apparently already the case. (I should definitely search more before opening new issues)

**Comment by maelle** [comment]
so https://ropensci.github.io/dev_guide/grooming.html#github-linguist is sufficient then? if not feel free to reopen.

**Comment by Bisaloo** [comment]
Yes, I'd say so. It's pretty close to what I had in mind anyways. 

If I were to modify it, I would maybe more explicitly say that repos that don't follow this tip might not appear in search results with the `language: r` filter, as I mentioned in my first comment.

The current phrasing ("more discoverable") might not be clear enough to someone who didn't encounter this issue first hand.

**Comment by Bisaloo** [comment]
On a related note, are you sure that files in `docs` are ignored by default?

> If you store html files in non standard places (not in docs/, e.g. in vignettes/)

See e.g. https://github.com/ropensci/rdflib. I seem to remember that we also had to manually override linguist settings for this in `pavo`.

**Comment by Bisaloo** [comment]
Hum, according to linguist docs, yes, it should be ignored. 

https://github.com/github/linguist#documentation

I'm not sure why `rdflib` is marked as HTML then.

**Comment by maelle** [comment]
can you open a small PR for the updated phrasing please? :-)
