### ISSUE TITLE
Update blog post stuff in the approval template?

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#180]
cc @stefaniebutland (templates/approved.md)

**Comment by sckott** [comment]
@maelle @stefaniebutland what exactly needs to be done here?

**Comment by stefaniebutland** [comment]
LGTM as is

**Comment by stefaniebutland** [comment]
LGTM. 
I will continue to take blog posts or tech notes from authors who wish to do these, and the text as is, is good.

Where is the right place in dev guide for the handling editor to see/do this:

> Nominate a package to be featured in an rOpenSci blog post or tech note if you think some aspect of it might be of high interest. Please note in the software review issue one or two things the author could highlight, and tag @stefaniebutland for follow-up.

**Comment by sckott** [comment]
What looks good to you? you mean to leave it as is? 

> Where is the right place ...

probably in this checklist id imagine https://devguide.ropensci.org/editorguide.html#editorchecklist - i'll add in there unless anyone disagrees

**Comment by stefaniebutland** [comment]
yes, leave as is

8.2.4 https://devguide.ropensci.org/editorguide.html#editorchecklist looks like the right place, thank you
