### ISSUE TITLE
pkgreviewr requires RStudio

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/dev_guide#183]
Section **7.1.3 Helper package for reviewers** has instructions for installation and using but fails to specify that you _must_ be using RStudio to use this package. I don't have a problem with that, I use it, but got caught out because I was just using radian and it gave me an error message.

Would be good to specify that RStudio needs to be used for this functionality in this section.

**Comment by annakrystalli** [comment]
Thanks for this comment @adamhsparks! Fair point and I'll add it to the docs.
