### ISSUE TITLE
Advice on specifying dependency minimum versions

### ISSUE THREAD

**Issue by annakrystalli** [ropensci/dev_guide#185]
Incorporate discussion on excessive use of minimum versions of dependencies. @karthik's post summarises the issue well:

> Specifying minimum dependencies should be a conscious choice. If you know for a fact that your package will break below a certain dependency version, specify it  explicitly.
But if you don’t, then no big deal. In that case when a user reports a bug which is explicitly related to an older version of a dependency then address it then.

> An example of bad practice would be for a developer to consider the versions of their current state of dependencies to be the min. That would needlessly force everyone to upgrade (causing issues with other packages) when there is no good reason behind that version choice.

**Comment by maelle** [comment]
@karthik can we use your summary above?
