### ISSUE TITLE
Deployment changes

### ISSUE THREAD

**Issue by sckott** [ropensci/dev_guide#188]
So we can see the result of changes in the book

**Comment by sckott** [comment]
ok

**Comment by maelle** [comment]
we need 3 GH actions workflows, maybe
- for push to master, push to gh-pages
- for push to dev, publish to Netlify site (prod)
- for PR, publish to Netlify site (not prod, draft), and have the deploy URL posted as commit comment?

**Comment by maelle** [comment]
- [ ] have a fallback for the list of reviewers in order not to always need the Airtable API key.
- [ ] after next release, [prevent autobuild on Netlify for the dev site](https://sung.codes/blog/2019/12/25/building-gatsby-with-git-hub-actions-and-deploying-to-netlify/)

**Comment by maelle** [comment]
Actually if someone opens an external PR, we would only get a preview if
1. there were a fallback for the reviewers list.
2. the contributor had a NETLIFY_AUTH_TOKEN in the settings of their fork (and we'd need some logic in the workflow to use a random website, not our Netlify website).

Because of 2. I think it's too cumbersome?

**Comment by maelle** [comment]
* I've added logic (at each step, it didn't work for the whole job / I didn't find out how) to skip all the PR workflow when the PR is from an external repo.

* For master, things won't work until after dev is merged.

**Comment by maelle** [comment]
After dev is merged into master, 

- [ ] check the master workflow works + delete anything related to Travis.
- [ ] unlink the Netlify site from GitHub (or maybe let it be linked? probably doesn't matter too much that it's linked)

**Comment by maelle** [comment]
no need to unlink, we still use the dev-site branch!
