### ISSUE TITLE
Make adding links to docs.ropensci.org part of approval template

### ISSUE THREAD

**Issue by noamross** [ropensci/dev_guide#191]
Adding docs.ropensci.org as URL and such should be part of the approval template.  Since there's some information about this in the FAQ that @jeroen sent to package authors, we should add this somewhere in the dev guide so that we can link to it.

**Comment by maelle** [comment]
Related to #162 (that did not add all the elements mentioned above)

**Comment by maelle** [comment]
Or maybe it did 🤔

**Comment by maelle** [comment]
@sckott might be good to have this in the current milestone as part of the changes related to docs?

**Comment by sckott** [comment]
sounds good
