### ISSUE TITLE
README instructions

### ISSUE THREAD

**Issue by sckott** [ropensci/dev_guide#192]
i assume 

> and the book will be generated in an `_output` folder.

in the README section https://github.com/ropensci/dev_guide#notes-for-associate-editors is incorrect? I do see a `_book` folder, but no `_output` folder

**Comment by maelle** [comment]
Yes sorry this might be the name of the folder on Travis or just a stupid mistake. I almost never generated the book locally btw, relied on Travis rendering master and dev 🙈

**Comment by sckott** [comment]
ok, will fix in dev branch 😸
