### ISSUE TITLE
New Zenodo DOIs not triggered with new releases

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/dev_guide#195]
Clicking the Zenodo badge link https://doi.org/10.5281/zenodo.2553043 takes you to first release, not current release.

From Scott:
![Screen Shot 2019-10-02 at 9 57 12 AM](https://user-images.githubusercontent.com/11927811/66065359-0e0aef80-e4fc-11e9-8326-5e2f640c9a29.png)

**Comment by maelle** [comment]
Apparently I didn't set it up correctly. Not sure where to look, where is this dashboard with failures? Does one see error messages? Sorry for messing it up.

**Comment by maelle** [comment]
Where does the dashboard screenshot come from?

**Comment by maelle** [comment]
```
 "errors": "Unknown error occured."
```

super helpful... will investigate more tomorrow.

**Comment by maelle** [comment]
I had not updated the Zenodo metadata.

I won't experiment with this until #202 is fixed.

**Comment by maelle** [comment]
Once I figure this out I will update the release guidance.

**Comment by maelle** [comment]
My understanding is that the steps are
* edit https://github.com/ropensci/dev_guide/blob/master/.zenodo.json
* and then make the GitHub release.

@noamross is that consistent with your experience using Zenodo?

**Comment by noamross** [comment]
Yes. Zenodo's uptake of the JSON file is super finicky and I get failures all the time like this when I edit the file and then release. At least now it reports what the error was when you click on those failed versions. They don't provide a validator so there's not really a solution except creating and deleting more releases.

**Comment by maelle** [comment]
Thank you! I'll experiment once dev has been merged into master, then. Too bad there's no validator.

**Comment by maelle** [comment]
Yay unknown error... I'll delete and start again.

**Comment by maelle** [comment]
Ok so 1,000 tries later... it's sort of fixed. I had to make the licence "other-open" which is the licence there was last time the Zenodo thing worked.

@noamross do you have any example of a Zenodo JSON file indicating "Creative Commons Attribution 4.0 International"? We have the licence file in the release, but it'd be nicer to also have it in the metadata. The "Creative Commons Attribution 4.0 International" licence is a choice when one look into uploading something on Zenodo website but I wasn't able to find how to format it in the JSON.

**Comment by maelle** [comment]
ping @noamross :slightly_smiling_face:

**Comment by noamross** [comment]
I didn't, but this one seems to be working correctly: https://github.com/tufts-carpentries/spreadsheets-engineering/blob/2587dcfacb0139f722ace8be879ebb73231789d5/.zenodo.json

All I did was search: https://github.com/search?q=filename%3A.zenodo.json+license+CC+4

**Comment by maelle** [comment]
Oh no why did I only think of Zenodo search 🙈 thanks
