### ISSUE TITLE
Section 1.3 Package API is blank

### ISSUE THREAD

**Issue by corburn** [ropensci/dev_guide#198]
The documentation contains a header for a [Package API](https://devguide.ropensci.org/building.html#package-api) section, but there is no content. I don't know if it is a placeholder or if it was forgotten.

**Comment by sckott** [comment]
thanks for the heads up on this @corburn  We'll have a look and get it sorted

**Comment by maelle** [comment]
Good catch @corburn! We forgot a "#" for the header below, "Package API" is the section above the three subsections below. It will be fixed in https://devdevguide.netlify.com/ (dev version of the guide) as soon as the change is deployed.
