### ISSUE TITLE
Deploy failure

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#203]
LaTeX error https://travis-ci.org/ropensci/dev_guide/builds/601646840#L2733

**Comment by maelle** [comment]
I am not able to reproduce this error locally.

**Comment by maelle** [comment]
but I can reproduce it with gh actions, cool...

**Comment by maelle** [comment]
SUCH RELIEF

**Comment by yihui** [comment]
FYI I just fixed this issue in **rmarkdown**: https://github.com/rstudio/rmarkdown/commit/2faf16a8bc4755569250fd426b0c5080888de2a0.

**Comment by maelle** [comment]
Yay and thanks for telling us!

**Comment by yihui** [comment]
You are welcome! And the new version of rmarkdown (2.1) is on CRAN now.
