### ISSUE TITLE
add more guidance reg http testing

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#208]
https://discuss.ropensci.org/t/best-practices-for-testing-api-packages/460

https://ropenscilabs.github.io/http-testing-book/

**Comment by maelle** [comment]
@sckott does your HTTP testing book have "releases"?

**Comment by sckott** [comment]
no, i don't think it's on a big enough "stage" to warrant it

**Comment by maelle** [comment]
Revisit this once the book has had improvements. The dev guide would then probably simply link to it.

**Comment by maelle** [comment]
The book is getting updated, but I'm not sure what we should recommend/request of package authors.

**Comment by maelle** [comment]
The book is now mentioned in the packaging guide. For any specific _requirements_ I feel we need a bit more feedback on the book & the presented workflows.

**Comment by maelle** [comment]
@mpadge what is your opinion on _requiring_ some aspects of HTTP testing? maybe out of scope?

**Comment by mpadge** [comment]
I think not out of scope, but options for http testing are both (1) changing rapidly, and (2) sufficiently diverse that to do anything other than point folk to the book would likely be unnecessarily prescriptive. So i'd say close this for now, and revisit later if we want.
