### ISSUE TITLE
Document best way to handle BioConductor package dependencies for CRAN packages.

### ISSUE THREAD

**Issue by noamross** [ropensci/dev_guide#210]
~~Packages on CRAN can have BioConductor dependencies but they need the empty field `biocViews:` in their DESCRIPTION for installation to work properly.  This is under-documented around the web so it will be useful to put it in the packaging guide as another way to find it.~~

~~https://bioinformatics.stackexchange.com/questions/3365/r-package-development-how-does-one-automatically-install-bioconductor-packages~~

The above is wrong but we should note the best way for packages to rely on BioConductor pacakges.

**Comment by maelle** [comment]
would you like to make a PR for that @noamross? :-)

**Comment by maelle** [comment]
@noamross how does this work?! I can't find the related code via https://github.com/wch/r-source/search?utf8=%E2%9C%93&q=biocViews&type= and I only know of the [`remotes` support](https://devtools.r-lib.org/articles/dependencies.html#other-sources)

**Comment by maelle** [comment]
For https://cran.r-project.org/web/packages/aroma.core/ (where Bioconductor packages have correct links), the DESCRIPTION file as a [DependsNote](https://github.com/HenrikBengtsson/aroma.core/blob/23a44acc5d5d2bf50aebc93637fd5b22accb4cb8/DESCRIPTION#L8).

**Comment by noamross** [comment]
Oh wow I have no idea and now I am very curious.

**Comment by maelle** [comment]
https://stat.ethz.ch/pipermail/bioc-devel/2015-March/007064.html

**Comment by maelle** [comment]
Relevant `tools:::.get_standard_repository_URLs()`

**Comment by maelle** [comment]
https://github.com/wch/r-source/commit/94c4f33e06a7f35be0d8ebf7c195de533fa375a4

**Comment by maelle** [comment]
https://stat.ethz.ch/pipermail/r-package-devel/2016q3/000909.html

**Comment by maelle** [comment]
https://support.bioconductor.org/p/124812/

**Comment by maelle** [comment]
It seems to be that there's no need to add anything to DESCRIPTION, i.e. one can handle Bioc dependencies like CRAN dependencies.

**Comment by maelle** [comment]
The user needs `getOptions("repos")` to return the necessary Bioc repo(s). See https://github.com/bioimaginggroup/nucim#installation (tested).

**Comment by maelle** [comment]
Now I'm not sure installing Bioc packages like that is recommended?!

**Comment by maelle** [comment]
https://www.bioconductor.org/install/index.html#why-biocmanagerinstall is interesting too.

**Comment by noamross** [comment]
OK, so my original note above is wrong, I think. `biocViews` is actually something need if your package is on _Bioconductor_.

Perhaps the recommendation should just be that README and other documentation indicate the preferred way to install bioC dependencies - e.g., add `https://bioconductor.org/packages/[X.X]/bioc` to your `repos` options, or use *biocLite*.

Since CRAN and BioC have different release models, should best practice be to note the Bioconductor release version in DependsNote or something similar?  @gmbecker or @HenrikBengtsson, perhaps you could advise?

**Comment by annakrystalli** [comment]
So it appears from this [issue](https://github.com/r-lib/remotes/issues/380) that `BiocViews:` field points to the fact that some dependencies are hosted on the bioconductor remote. 

Indeed adding a `BiocViews:` field solved a missing dependency error when I was trying to install the following package: `https://github.com/llrs/BaseSet`, 
eg to reproduce the errors, ensure you do not have `BiocStyle` and `org.Hs.eg.db` packages installed and compare errors between:
```r
devtools::install_github("llrs/BaseSet", dependencies = T, build_vignettes = T)
```
and my fork with added `biocViews:` field.
```r
devtools::install_github("annakrystalli/BaseSet", dependencies = T, build_vignettes = T)
```
However, it does not work for Bioconductor packages with no binaries available.  

For example, it does not install `org.Hs.eg.db` successfully. Indeed, even following the Installation instructions on the package's bioconductor page fails:
> ### Installation
> To install this package, start R (version "3.6") and enter:
> 
> ```r
> if (!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
>
> BiocManager::install("org.Hs.eg.db")
> ```

I get:

```
Bioconductor version 3.10 (BiocManager 1.30.10), R 3.6.0 (2019-04-26)
Installing package(s) 'org.Hs.eg.db'

   package ‘org.Hs.eg.db’ is available as a source package but not as a binary

Warning message:
package ‘org.Hs.eg.db’ is not available (as a binary package for R version 3.6.0) 
```
It also prompts me to upgrade the just installed  `BiocStyle`.
```
Old packages: 'BiocStyle'
Update all/some/none? [a/s/n]: 
a
trying URL 'https://bioconductor.org/packages/3.10/bioc/bin/macosx/el-capitan/contrib/3.6/BiocStyle_2.14.4.tgz'
Content type 'application/x-gzip' length 956336 bytes (933 KB)
==================================================
```
Indeed the `BiocStyle` version installed  (**2.12**) through `DESCRIPTION` file and `BiocViews:` was not most recent. When accespting the prompt to update I get **`BiocStyle` 2.14**

In the end I managed to successfully install `org.Hs.eg.db` with:
```r
BiocManager::install("org.Hs.eg.db", type = "source")
```

So it seems that `BiocViews:` does work (and I've had it work for other packages with bioconductor packages) but it does not necessarily install the most recent version, it does not work for source packages and the error messages are not very informative during installation of the dependent package, only when the failing dependecy is attempted to be installed the bioconductor way.

**Comment by llrs** [comment]
BiocViews is required by Bioconductor to classify the packages for easier finding of packages (now they are also experimenting with [BioSchema](https://github.com/Bioconductor/bioconductor.org/pull/25)). This allows to search for similar packages according to what they do, [like this](http://bioconductor.org/packages/release/BiocViews.html#___Software). I also have used in the past to indicate that there are some dependencies on Bioconductor. But I think it is not needed because there are some packages, like [WGCNA](https://cran.r-project.org/package=WGCNA), that depend on Bioconductor packages (GO.db) that don't have it on the DESCRIPTION file. 

The recommended and official way to install the Bioconductor packages is using `BiocManager`. However, I am not sure how are the binaries built for Windows (Linux and OS builds are generally made available). In principle they should be available too, but the builders had some troubles for some weeks. I don't know of any heuristics to decide when one should install a package from source or using binaries. AFAIK the only solution is to try the binaries and if they fai, then build from source. 

The latest version of Bioconductor is not granted in any case. `BiocManager::valid()` checks if the Bioconductor's (and CRAN) packages are on the latests version available for the R version you are using. 

(Note that BiocManager import also remotes and you can install from github directly with `BiocManager::install("llrs/BaseSet", dependencies = TRUE, build_vignettes = TRUE)`. Perhaps you could [fill a bug](https://github.com/Bioconductor/BiocManager) to reinstall from source when the binaries are not available.)

**Comment by annakrystalli** [comment]
Thank you so much for commenting @llrs ! It really helped clarify things for me.

POSTING RESPONSE FROM REVIEW ISSUE HERE FOR rOpenSci policy discussion

> Aha, it seems I have been trying to install the package the wrong way all this time, by using `devtools::use_github()` as I normally do for editors checks when I should be using `BiocManager::install()`

> However, when I try to install using `BiocManager::install("llrs/BaseSet", dependencies = TRUE, build_vignettes = TRUE)` I still get the same errors for a couple of suggested bioconductor packages I removed to test it out.

> I'm really intrigued by the fact that the packages builds successfully for you on TRAVIS. Looking at your `travis.yml` I see you are testing on `r: bioc-devel` only. I think this where the testing computational environment and my own (and of reviewers and future collaborators) would differ.  I feel also testing on `r: release` at the very least would give a better idea of what challenges others would encounter. Would you mind trying that out for me?

**Comment by maelle** [comment]
A further issue might be opened if the current text can be improved for CI aspects. Thanks everyone for your input!
