### ISSUE TITLE
Add sthg about tests of deprecated functions?

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#213]
https://community.rstudio.com/t/unit-testing-of-a-deprecated-function/42837/2

**Comment by sckott** [comment]
I guess I usually don't change the tests of deprecated functions until they are made defunct, then their tests are removed. But thinking about it and looking at that thread:

- Consider any changes made to a deprecated function. Along with using `.Deprecated` inside the function, did you change the parameters at all in the deprecated function, or create a new function that replaces the deprecated function, etc. Those changes should be tested if any made. 
- Related to above, if the deprecated function is simply getting a name change, perhaps test that the old and new functions return identical results
- `suppressWarnings()` could be used to suppress the warning thrown from `.Deprecated`, but tests are not user facing, so not a huge deal if its thrown in tests, and may be a good reminder to the maintainer
