### ISSUE TITLE
enforce repo status badges?

### ISSUE THREAD

**Issue by sckott** [ropensci/dev_guide#22]
Should we if a package is using an alternative set (e.g., life cycle) 

e.g., here’s a case of someone using a lifecycle badge https://github.com/nbenn/infx#infx in onboarding 

I think we should make them change to repostatus since we’re going to use badges to categorize our pkgs

**Comment by maelle** [comment]
I think we should, I suggested here as an issue to have this as a guideline.

**Comment by maelle** [comment]
Related to https://github.com/ropensci/codemetar/issues/169
