### ISSUE TITLE
What approach for precompiling vignettes

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#220]
for the docs server / for CRAN

One example https://github.com/jeroen/jsonlite/blob/master/vignettes/precompile.R

**Comment by maelle** [comment]
cc @dpprdan :-)

**Comment by maelle** [comment]
instead of recommending one approach we could document several ones, along with the way to automate them.

**Comment by dpprdan** [comment]
Re "several approaches" I'll just reference https://github.com/r-lib/pkgbuild/issues/58#issuecomment-559791789. I haven't tried it though, so cannot comment on its pros and cons vis-a-vis simply (?) precompiling.

**Comment by maelle** [comment]
Link to Jeroen's tech note https://ropensci.org/technotes/2019/12/08/precompute-vignettes/
