### ISSUE TITLE
How do I cite the dev guide?

### ISSUE THREAD

**Issue by HeidiSeibold** [ropensci/dev_guide#239]
I'd like to cite the book in a paper. What is the best way to do so?

**Comment by maelle** [comment]
Thank you 😍 We have a Zenodo badge in the README. Sadly it is for the first version of the dev guide (see #195 ). I intend to fix that with the next release in a few weeks. When do you need the DOI? I can make a release of current master next week (Wednesday) if it can help.

**Comment by HeidiSeibold** [comment]
For me it only matter that the version I cite contains the review instructions and the template. Thanks @maelle 

Btw: I really did try figuring out how to cite it myself. Maybe it could be a bit more prominent?

**Comment by maelle** [comment]
You're right (and I have no doubt you tried!), where would you like to find the info?

* In the README
* In the book (it's at the very bottom of https://devguide.ropensci.org/ but I'm guessing it's hidden, where else would you expect it?)

**Comment by HeidiSeibold** [comment]
So I looked / would expect

- Dook (beginning, somewhere close to the license)
- CITATION.md in the repo
- Somewhere in README.md

Any would be fine, I guess. Maybe I was also just a bit blind :stuck_out_tongue_winking_eye:
