### ISSUE TITLE
Clarify section on Code of Conduct?

### ISSUE THREAD

**Issue by cboettig** [ropensci/dev_guide#240]
Our advice (and reviewer checklist) asks for the code of conduct to be linked and suggests using the usethis function, https://devguide.ropensci.org/collaboration.html#friendlyfiles.  This means that most developers will use the default `usethis` code of conduct.  Two questions:

1) Wouldn't it be better for us to tell authors to add a link to ropensci's code of conduct at https://ropensci.org/code-of-conduct/ ?  If not, then I'm a bit confused about the scope of both codes.  I know a 'contributor code of conduct' is a bit narrower in scope than the the ropensci code of conduct, but it seems the latter should cover the former as well, and seems kinda like I'm opting out if I'm declaring my package to be governed by a separate code of conduct (with no constraint on what I'm expected to actually list there if I do deviate from the usethis template).  

2) The usethis function directs the user to paste this block into the README:

```
[Contributor Code of Conduct](CODE_OF_CONDUCT.md).
```
I always paste this exactly, and then almost without fail I get the package rejected from CRAN for having a URL that doesn't resolve.  (This is fixed in the dev version but for now most users probably still have the CRAN version of `usethis`, https://github.com/r-lib/usethis/pull/917)

**Comment by cboettig** [comment]
Thoughts from our code of conduct committee team @stefaniebutland @sckott @karawoo appreciated here too!

**Comment by sckott** [comment]
hmm, the one on our website is more comprehensive. we do want folks to have a code of conduct file in their repo for sure though. maybe we could suggest a COC file that links out to the COC on our website?

yeah, the coc url instead of path link should be made clear - i don't use usethis, but good to see they're updating it.

**Comment by maelle** [comment]
cf also https://discuss.ropensci.org/t/using-ropensci-code-of-conduct-on-github-project/1898

**Comment by maelle** [comment]
cc @Bisaloo

**Comment by maelle** [comment]
@stefaniebutland @karawoo would it make sense if the dev guide stated the COC after transfer should be a link to rOpenSci COC?

**Comment by maelle** [comment]
In the absence of response above, I'm removing this item from next release. Thanks for your understanding.

**Comment by stefaniebutland** [comment]
I've opened an issue for the Code of Conduct Committee to make a decision and specific recommendation. This is not likely to happen before May (sorry).

**Comment by stefaniebutland** [comment]
Sorry it took me a while to wrap my head around this. I agree with the current suggestion to link to rOpenSci's Code of Conduct. Since Scott also agreed I don't think this requires further discussion with Kara since it doesn't influence the Code of Conduct itself.

**Comment by maelle** [comment]
Thanks @stefaniebutland and @sckott.

@sckott (and anyone who wants to chime in) a few questions

* so in practice after approval of the package should CODE_OF_CONDUCT.md content be

```
Refer to [rOpenSci Code of Conduct](https://ropensci.org/code-of-conduct/)
```
?

* And what about the COC _before_ review? Do we require one? Here's the current content on COC in the dev guide https://devdevguide.netlify.com/collaboration.html#code-of-conduct-1

* what about existing code of conducts in packages that have been onboarded a while ago? Do we want to do a PRs campaign to update them?

**Comment by maelle** [comment]
https://github.com/search?l=&q=user%3Aropensci+filename%3ACODE_OF_CONDUCT.md&type=Code

https://github.com/search?l=&q=user%3Aropensci+filename%3ACONDUCT.md&type=Code

:grimacing:

**Comment by sckott** [comment]
what's in your PR looks good

**Comment by Bisaloo** [comment]
A good first step would be to update the approval template so that newly approved packages follow the latest guidelines :wink:

**Comment by maelle** [comment]
That's a good suggestion but I'm a bit undecided: if new packages were built using usethis, or GitHub docs, they'll most likely already have the right filename. And the approval list is long. So probably better as an editor check :thinking:

**Comment by maelle** [comment]
wait I got confused, I need to update the approval template indeed :woman_facepalming:

**Comment by maelle** [comment]
The approval template had been updated.

Now what's needed is making sure old packages follow the new guidelines.
