### ISSUE TITLE
Updating high-level review guide principles

### ISSUE THREAD

**Issue by noamross** [ropensci/dev_guide#25]
The high-level principles in the reviewers' guide could probably stand to be updated, to reflect some of the themes that have made their way into the packaging guide in low-level standards, such as:

-  Documentation should use the principle of multiple points of entry
-  Functions and arguments naming should be chosen work together to form a common, logical programming API that is easy to read, and autocomplete.  
    -  (The following may be low-level, and are partially in the packaging guide, but should somehow be linked to the above)
    -   Function names should follow a consistent scheme using prefixes, verbs, and objects.
    -   Argument naming and order should be consistent across functions that use similar inputs.  Data being operated on should generally be the first argument(s), with options and parameters following.

**Comment by maelle** [comment]
@noamross could you clarify what you mean by "Documentation should use the principle of multiple points of entry"? Your other points have made their way to chapter 1.

**Comment by noamross** [comment]
As I recently wrote in the **rcites** review, where I phrase it slightly differently:

> Remember the _principle of first entry_ - any piece of documentation may be the first encounter the user has with the API, data source, or even the CITES treaty/organization.

Basically, this means the README, the top-level package docs, vingettes, websites, etc., should all have enough information at the beginning to get a high-level overview of the package and the services/data it connects to, and provides navigation to all the other relevant pieces of documentation.  I think this is especially important because of the number of websites out there like Rdocumentation, which suck up and aggregate various types of documentation in ways you don't control.
