### ISSUE TITLE
text about release posts

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#256]
@stefaniebutland in https://devdevguide.netlify.com/marketing.html We say "Consider submitting a technote about the release to rOpenSci technotes blog. Contact Stefanie Butland, rOpenSci community manager, (e.g. via Slack or stefanie@ropensci.org ). The guidelines about contributing a blog post can be found here)." apart from the here link does this need updates?

**Comment by stefaniebutland** [comment]
Thanks for asking. Minor text edits:

Consider submitting a short post about the release to rOpenSci tech notes. Contact Stefanie Butland, rOpenSci Community Manager, (e.g. via Slack or stefaniebutland@gmail.com). The guidelines for contributing a post can be found here).
