### ISSUE TITLE
add precommit hooks

### ISSUE THREAD

**Issue by mpadge** [ropensci/dev_guide#268]
Default [precommit hooks](https://github.com/lorenzwalthert/precommit) do a spell check on commit, and I've got a custom one in [`statistical-software-peer-review`](https://github.com/ropenscilabs/statistical-software-peer-review/blob/master/scripts/chunknames) that prevents commits in which any chunks have blank names, or in which any have duplicated names across any of the chapters. The latter is especially useful as a pre-debug prior to github actions building book and failing because of duplicated chunk names.

**Comment by maelle** [comment]
Thank you for the suggestion! I'm still undecided because it requires more setup to be useful. :thinking:

**Comment by mpadge** [comment]
The beauty of it is that it is only triggered if you have actively installed [precommit hooks](https://pre-commit.com/) within your git tree. If you haven't done that, the `.pre-commit-config.yaml` will simply be ignored. It's a strictly opt-in system only which can be there if you desire, but all others will always be free to ignore it.

**Comment by maelle** [comment]
I know but if it's ignored by, say, all contributors but me, it's not really useful, hence my wondering.

**Comment by mpadge** [comment]
> I know but if it's ignored by, say, all contributors but me, it's not really useful, hence my wondering.

yeah, that be true. ultimately both here and with the stats book we'll be better off modifying the PR workflow to add an action to check chunk names. Ooooh yeah, that's a good idea! Shall i rename this issue, or would you prefer to just close it here (not like you don't a million other things you're busy with right now!) and open an issue over yonder?

**Comment by maelle** [comment]
as you prefer! :-)

**Comment by mpadge** [comment]
To save you work, I'll close here, and PR directly to your workflows once it's up and working for the stats book. Thanks!

**Comment by maelle** [comment]
thank _you_ for sharing your good ideas!!
