### ISSUE TITLE
Suggest maintainers remove all hyperlinks?

### ISSUE THREAD

**Issue by sckott** [ropensci/dev_guide#281]
CRAN checks urls throughout package documentation. One can argue that on its own this is good. However, compared to getting a critical bug fix up, link checking in documentation is not important at all. 

I have been removing all hyperlinks in my packages to avoid delays on getting new versions up on CRAN. In our docs sites, the links are still hyperlinked, so users don''t have to copy/paste them, but then CRAN's url checking scripts just ignore them if they are just plain text. 

Do others agree we should suggest removing hyperlinks in package docs?

**Comment by maelle** [comment]
That's an interesting idea to solve the problem.

I suppose the problem is that there is a trade-off since it means the local docs have non clickable links?

Have you removed the hyperlinks by hand? Is there an example commit you can link to?

**Comment by sckott** [comment]
True, local docs wouldn't have clickable links. 
What I do is just remove the markdown or latex syntax, so change `<https://ropensci.org/>` to `https://ropensci.org/`, or `\url{https://ropensci.org/}` to `https://ropensci.org/`. 
It would be nice to retain the clickable links locally, but its just too painful for cran submissions so i'd suggest maintainers remove link syntax

**Comment by maelle** [comment]
I realize I have another question before adding this to the dev guide, sorry. How do _you_ check URLs for ensuring they don't go stale?

**Comment by sckott** [comment]
Oh and you don't have to agree with me about this. 

Maybe we could provide a short script for checking urls in a package? Something like  https://github.com/ropensci/biweekly/blob/gh-pages/scripts/check_urls.R for the newsletter

**Comment by sckott** [comment]
One thing i noticed, seems CRAN still checks URLs in vignettes and README (probably all markdown files) even if the link is just plain text, so that sucks.

**Comment by maelle** [comment]
right, so I think we can't make exhaustive guidance in the dev guide yet, as there are still questions

* How does one still check URLs

* How does one prevent false positives when CRAN checks emails in vignettes and README (or how does one prevent this CRAN check)

**Comment by maelle** [comment]
Actually thanks to the Slack convo I have enough material.
