### ISSUE TITLE
cran submission topic to maybe add?

### ISSUE THREAD

**Issue by sckott** [ropensci/dev_guide#283]
https://twitter.com/mcguinlu/status/1314262862060294144

> question: is it acceptable to push a new version of a package to CRAN within two weeks of the most recent version if you have just been made aware of, and fixed, a major bug? I know they don't like super-frequent submissions, but this bug is bad?

**Comment by maelle** [comment]
right this is an excellent question. What is your own answer to it?

When I saw this tweet I actually started dreaming of a blog post (maybe R-hub) where there would be such etiquette questions.

**Comment by sckott** [comment]
I was thinking "it depends". Since its humans on the other hand, they're all different, so some may stick to the rules and not allow but some may allow it. I would say try and make the case in cran comments, can't hurt.

**Comment by maelle** [comment]
I'll push this to next release.
