### ISSUE TITLE
Clarification on responsiveness to CRAN

### ISSUE THREAD

**Issue by llrs** [ropensci/dev_guide#295]
I was reading about the maintenance of a package and the role of rOpenSci.

The [guidelines](https://devguide.ropensci.org/policies.html#maintainer-responsiveness) says: "If package maintainers do not respond in a timely manner to requests for package fixes from CRAN ".
How would rOpenSci know this? Presumably only the maintainer of the package receives the notifications. 

I'm interested because I would like to collaborate and improve a package on rOpenSci but the maintainer is not responsive (last commit almost a year ago, many pending issues and pull requests and has a couple of notes on several machines on CRAN). I've message via slack three months ago but didn't receive any reply. I haven't send any email, (as I too don't want to commit to too many things), but I would like to help the maintainer somehow.

**Comment by maelle** [comment]
This is an excellent question. Any general advice @sckott?

Regarding the package in particular, can you message me on Slack so I might see what we can do?

**Comment by llrs** [comment]
So we should contact the editor that handled that package ? As the only other person able to change permissions to that repository, if my understanding of teams and organizations is right. 

Despite my example/case, this issue is more about how does rOpenSci know the "timely manner" of fixes from CRAN. Or does it only step in when the package is removed from CRAN? (Do you have some notification system set up for this? )

**Comment by sckott** [comment]
> So we should contact the editor that handled that package ?

No, i meant ropensci staff. 

> how does rOpenSci know the "timely manner" of fixes from CRAN. Or does it only step in when the package is removed from CRAN? (Do you have some notification system set up for this? )

We don't have an automated system for this. We do generally find out pretty soon if a package is archived via various pathways. In the case of a pkg being archived, I will usually contact the maintainer and see if there's anything we (ropensci staff) can do to help. Often the maintainer states that they are "just really busy" or thereabouts.   It's rare that we get no response at all.

**Comment by llrs** [comment]
Oh, great! Many thanks

**Comment by sckott** [comment]
@llrs i assume you've contacted Maëlle?

**Comment by llrs** [comment]
Indeed @sckott, we chatted briefly on slack. I await what you (ropensci staff) decide/do, but on that package I'm willing to co-maintain.

**Comment by maelle** [comment]
Phrasing now clarified in the dev branch; and regarding the specific package mentioned, discussion in Slack. Thanks again for the issue!
