### ISSUE TITLE
Create spanish review template

### ISSUE THREAD

**Issue by FvD** [ropensci/dev_guide#301]
To document my review in Spanish as requested by @melvidoni I looked for a spanish language template. As I could not find it I made a translation.

I decided to name the file `review-es.md` and not a translated version of the file name so that the file content is still clear for a non-spanish speaker (`revision.md` would no be so hard to identify, but in other languages in the future this may be different).

**Comment by maelle** [comment]
https://devdevguide.netlify.app/reviewtemplatees.html

mentioned from https://devdevguide.netlify.app/reviewerguide.html

(this is the dev version of the dev guide, to be released soon-ish)
