### ISSUE TITLE
Clarify/improve dev guide citation

### ISSUE THREAD

**Issue by Bisaloo** [ropensci/dev_guide#304]
I'm trying to cite the dev guide in a paper. The book mentions

> Refer to [its Zenodo DOI](https://doi.org/10.5281/zenodo.2553043) to cite it.

But the reference proposed on Zenodo doesn't look so good:

> ### Cite as
>
> rOpenSci, Brooke Anderson, Scott Chamberlain, Anna Krystalli, Lincoln Mullen, Karthik Ram, … Julia Gustavsen. (2020, October 12). ropensci/dev_guide: Fourth release (Version 0.4.0). Zenodo. http://doi.org/10.5281/zenodo.4114295

- I would expect the title to be "rOpenSci Packages: Development, Maintenance, and Peer Review", which is the title you see when you open the book and that is [on the cover](https://devguide.ropensci.org/images/cover.png).
- As far as I can tell, it should be version 0.5.0, as correctly identified in other places in the Zenodo repository.
- It would also make sense IMO for the book to be identified as such (a book), which is not the case in the citation files on Zenodo (e.g., [bibtex file](https://zenodo.org/record/4114295/export/hx)).

I don't know if all this can be tweaked on Zenodo but otherwise, it would make sense to provide a reference (and possibly and bib file) directly on the guide, rather than requiring visiting an extra page, from which readers have to extract the reference (which might not be straightforward if you're not familiar with Zenodo, or at least less than some text directly in the book).

**Comment by maelle** [comment]
Thanks both for trying to cite the guide and for the issue! I always get so confused with Zenodo stuff.

Would you expect the citation to be provided in a bibtex format?
I am a bit undecided as it'd mean curating the author list in yet another place.

**Comment by maelle** [comment]
Another thing that's not great about the Zenodo proposed citation is that it removes author names in the middle...

I think https://github.com/ropensci/dev_guide/commit/fbc15a34fc796dedb55b3cae396e8c16b58e7977 should at least improve the title and version number after the next release.

**Comment by maelle** [comment]
I added `"publication_type": "book"`

**Comment by maelle** [comment]
So what remains is maybe adding a citation example.

**Comment by Bisaloo** [comment]
Regarding your first two points, Zenodo already provides a bibtex file that contains all the author names: https://zenodo.org/record/4114295/export/hx. It's correctly imported by the Zotero add-on as well.

>  I am a bit undecided as it'd mean curating the author list in yet another place.

Hmm, makes sense. What about using the bibtex file on Zenodo to auto-generate the citation in the book?

**Comment by maelle** [comment]
ah good idea, I'll see if I can easily get it programmatically! Maybe the occasion to explore zen4R. https://github.com/eblondel/zen4R

**Comment by maelle** [comment]
@Bisaloo After the next GHA run there will be the same info in the preface and first page: https://devdevguide.netlify.app/index.html

![image](https://user-images.githubusercontent.com/8360597/105707040-a22f7000-5f12-11eb-8bee-40ef7936c13c.png)

I hope the changes I made in the Zenodo metadata will tackle other problems (better title, correct version number, book).

Any further comment? Thanks again for the issue!
