### ISSUE TITLE
More contributing guide guidance?

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#308]
cf https://github.com/ropensci/opencage/pull/128#issuecomment-776858806 by @dpprdan 
Linked to #289

**Comment by maelle** [comment]
@stefaniebutland maybe if there were more guidance about how to contribute to a package it should live in the contributing guide, and the contributing guide of repos would point to that?

**Comment by maelle** [comment]
Or maybe it should live in the dev guide, actually. :thinking:

**Comment by stefaniebutland** [comment]
I agree it should live in dev guide.

Idea of contributing guide is to point to the primary resources when they exist, not to host the resources. If/when more details are in dev guide we would reduce the [text in contrib guide](https://contributing.ropensci.org/resources.html#issues)
