### ISSUE TITLE
Add available as part of the editor checks?

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#313]
to check whether the package name is available.

**Comment by maelle** [comment]
@mpadge is this something that could go into an endpoint?

**Comment by mpadge** [comment]
Yep, please add to ropenscilabs/pkgreport#9, and I'll have a look. `available` is not exactly an automated check, and things like checking potentially inter-cultural offensiveness are very difficult to automate from the pages opened by `available`, but maybe there's some minimum stuff we can pull in and use regardless.
