### ISSUE TITLE
Tag and fix version when reviewers are selected

### ISSUE THREAD

**Issue by noamross** [ropensci/dev_guide#314]
Occasionally enthusiastic authors continue to make changes while reviewers are reviewing.  Would it make sense to ask authors to tag their repository to fix the version being reviewed? This should occur after editor checks, when we are seeking reviewers.  So this would be implemented by making this a step for editors.  It could be in the editor's template, but only used if the package passes this without need to update.

(Also relates to ropensci/software-review-meta#61)

**Comment by maelle** [comment]
@noamross how would you expect reviewers to handle this? cloning the repo at the tag?

**Comment by noamross** [comment]
Yeah, I'm inclined to agree with Scott that this is messier than initially thought.  It's more important that we record the version accepted.

**Comment by maelle** [comment]
Thank you!
