### ISSUE TITLE
check the presence of codemeta.json and CITATION file at submission

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#317]
cf https://discuss.ropensci.org/t/should-the-ropensci-dev-guide-include-package-citation-best-practices/1551/4

**Comment by mpadge** [comment]
@maelle if you keep a list of any of these kinds of things, I can add them to the endpoint so the bot can easily auto-check everything.

**Comment by maelle** [comment]
I'm wondering what makes more sense between adding to your bot or a custom buffy responder à la https://buffy.readthedocs.io/en/latest/responders/repo_checks.html :thinking: 

In any case I moved this to the dev guide because of #115

**Comment by mpadge** [comment]
> I'm wondering what makes more sense between adding to your bot or a custom buffy responder à la https://buffy.readthedocs.io/en/latest/responders/repo_checks.html thinking

That's the question which we really need to talk to @xuanxu about. I was going on the understanding you expressed previously that the bot/whole ruby system around it was effectively quarantined off from doing any actual computation, in which case it's pretty trivial and straightforward to deliver computationally expensive results from separate API endpoints which the bot can call. But that output in the `buffy` docs includes a standard `cloc` table, so the bot must be calling `cloc` internally. I don't know where the boundary lies between internally permissible actions and not?

**Comment by xuanxu** [comment]
Indeed `cloc` is [called internally](https://github.com/openjournals/buffy/blob/main/app/lib/utilities.rb#L22) with a standard call to the system.
There is not a quarantine to do any specific computation, other than "_You can only run what is allowed in the configutarion file_". 
So we could create workers to run anything as long as any needed dependency is installed in the system after deployment.
(All the expensive calls –those that could delay a response to github– are run by workers in background jobs)

I guess it's just a matter of thinking what makes more sense in each case: Adding code to run locally+installing and managing dependencies vs calling an external service.

**Comment by maelle** [comment]
@mpadge should I open an issue somewhere? Will a codemeta.json & CITATION file be compulsory for stat software review too?

**Comment by mpadge** [comment]
Yes, please add extra items to ropenscilabs/pkgreport#9 . Thanks!
