### ISSUE TITLE
Other types of package coverage

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#319]
Do we want to add a target for other types of package coverage?

https://covr.r-lib.org/reference/package_coverage.html

examples, vignette

related to https://github.com/ropensci/software-review-meta/issues/55#issuecomment-395487383

**Comment by maelle** [comment]
I would like to at least suggest using these different covr options to reviewers.

**Comment by mpadge** [comment]
Coverage of a vignette is interesting, but many are forced to have no running code, so coverage measures there do not reveal anything useful. Coverage of examples is a different issue, and one which I've got an extra endpoint for already, which currently just confirms that all exported functions include example code. I think that check is very useful, and more so than coverage of example code itself, which is also difficult to compare between packages. That said, I could easily include additional coverage form example code if desired?

**Comment by maelle** [comment]
Great explanation, thank you!

So maybe I should look into using that endpoint somewhere.
