### ISSUE TITLE
Delete text files from onboarding, move all links to dev guide

### ISSUE THREAD

**Issue by noamross** [ropensci/dev_guide#32]
We might as well do this now to avoid having two sets of docs. Would it also make sense to deprecate onboarding-meta and put all discussion in this repo?

**Comment by maelle** [comment]
Yes good idea will do. I won't delete them but instead put a link to here in them (because otherwise we're creating broken links).

I think there's not a perfect overlap between onboarding-meta and here, e.g. issues related to automation are better discussed there?

**Comment by maelle** [comment]
When should I transfer this repo to ropensci btw?

**Comment by noamross** [comment]
Anytime is fine with me.  @ropenci/editors?

**Comment by maelle** [comment]
well I'll do it now then 🚀

**Comment by maelle** [comment]
What about the README of onboarding, what should stay? Only a very general intro with a link to the dev guide; and the [how section](https://github.com/ropensci/onboarding#how-to-submit-your-package-for-review)? (the why sections are in the gitbook)

The dev guide has the reviewers' list but maybe we want it in the README too?

**Comment by maelle** [comment]
cf https://github.com/ropensci/onboarding/pull/228
