### ISSUE TITLE
goodpractice dev version

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#325]
is needed when `.Renviron` has

```
_R_CHECK_LENGTH_1_CONDITION_=verbose
_R_CHECK_LENGTH_1_LOGIC2_=verbose
```

reported by @adamhsparks.

Noting this here to not forget. We're making efforts to run goodpractice on a server but that is still good to know.

**Comment by mpadge** [comment]
@maelle can you please open same issue on [`pkgreport`]( https://github.com/ropenscilabs/pkgreport), and I'll ensure that runs on dev version
