### ISSUE TITLE
Add R-universe mention?

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#331]
Cc @jeroen 

* Should authors mention it as installation source in READMEs?
* Other things?

**Comment by jeroen** [comment]
Let's not enforce it, but we can suggest that package authors may mention in the readme that ropensci packages can be installed via 

```r
install.packages("pkg", repos = "https://ropensci.r-universe.dev")
```

I plan to write a technote about this soon, so once that is online, we can reference that technote.

**Comment by maelle** [comment]
Ah good then I'll wait for the tech note. Thank you!

**Comment by maelle** [comment]
https://ropensci.org/blog/2021/06/22/setup-runiverse/

**Comment by maelle** [comment]
authors could also add :sparkles: badges :sparkles:

**Comment by maelle** [comment]
https://github.com/ropensci/software-review/pull/481

**Comment by maelle** [comment]
https://github.com/ropensci/dev_guide/commit/71265761c008167428bb61273b3e1d73554ff737
