### ISSUE TITLE
Recommend curl::curl_download() over download.file()?

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#332]
@jeroen do you think such a recommendation would make sense in https://devdevguide.netlify.app/building.html#recommended-scaffolding?

**Comment by jeroen** [comment]
No, I think `download.file` works fine for simple cases. We can suggests that the curl package may offer more flexible tools, but if people want to stick with base R that is understandable. As long as they don't use `RCurl` 😄

**Comment by maelle** [comment]
Thank you! Yes we already have the guidance not to use RCurl!
