### ISSUE TITLE
Add contributing guide standards as a separate chapter 

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#334]
via https://github.com/ropensci/opencage/pull/128#issuecomment-776858806 from @dpprdan 

In #308 I'll only tackle adding more tips to the existing chapter.

**Comment by maelle** [comment]
@mpadge assigning you as it's part of the roadmap you wrote in https://github.com/ropensci/dev_guide/issues/366#issuecomment-990779938

**Comment by mpadge** [comment]
Closing this for now, as it'll all be addressed via #366, and PR #462. Contributing won't be a separate chapter, but i think that #462 makes expectations and requirements sufficiently more explicit.
