### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by Bisaloo** [ropensci/dev_guide#339]
I was looking for an opened devguide tab but couldn't find it because it has no favicon.

It might make sense (and it would be useful!) to add the rOpenSci favicon.

**Comment by maelle** [comment]
Thank you!

I think they are not supported by `bs4_book()` yet https://github.com/rstudio/bookdown/issues/1011

Now you'll have to open less tabs :stuck_out_tongue_winking_eye: (just kidding).

**Comment by mpadge** [comment]
Can't do anything here until upstream changes to `bookdown` linked to above, so bumping milestone to 0.9 for now.

**Comment by maelle** [comment]
Solved in the dev version, with Quarto https://devdevguide.netlify.app/

Cf https://quarto.org/docs/websites/website-tools.html#social-metadata
