### ISSUE TITLE
Policy about .DS_Store files?

### ISSUE THREAD

**Issue by annakrystalli** [ropensci/dev_guide#341]
I've noticed in a recent submission a lot of `.DS_Store` files in the package. I couldn't find anything in our docs about it.

- Do we have a policy about such files and if not should we?
- If we should I guess we should add it to our docs?
- It would also be something easy to check automatically as part of editor's checks. Is that worth it?

**Comment by mpadge** [comment]
Good point Anna. Maybe I should add another `pkgcheck` for files which definitely should **not** be included - like these. Can anyone think of any other files which shouldn't be part of a repo yet are commonly included?

**Comment by maelle** [comment]
Maybe one could use https://docs.ropensci.org/gitignore/reference/gi_fetch_templates.html to fetch a good list for R projects :-)

**Comment by annakrystalli** [comment]
Agree with @maelle's suggestion!

**Comment by maelle** [comment]
Handled in the dev branch (the building guide didn't even mention git!) + https://github.com/ropensci-review-tools/pkgcheck/pull/27

**Comment by mpadge** [comment]
[Here is the link](https://github.com/ropensci-review-tools/pkgcheck/blob/0cbf0080f0a5c6fc51aa1db500ed3a14f40945bb/R/misc-checks.R#L354-L357) to the definition of "unexpected files", currently including:

- `.DS_Store`
- `Thumbs.db`
- `.vscode`
- `^\\.o$`
