### ISSUE TITLE
Improve PDF output

### ISSUE THREAD

**Issue by mpadge** [ropensci/dev_guide#344]
Current pdf starts with 2 "junk" pages which don't seem necessary, and the pages after that are then in a strange order. It might help to add another line to the "Render Book PDF" step:

https://github.com/ropensci/dev_guide/blob/139027d02675cf0cc62142b4fb4d50dcba9db44d/.github/workflows/master.yml#L56

to do a simple `pdftk` rearrangement of the first few pages. (And extend current `brew install libgit2` to `pdftk`.)

**Comment by maelle** [comment]
what pages?

**Comment by mpadge** [comment]
It seems to me that pages 1-2 are just auto-generated junk that aren't needed, especially because page 1 is an auto-title on which authors occupy a single line so only the first few are readable. Page 2 is blank, then comes contents. After that, page 10 is the cover image, which I'd suggest should be page 1. Pages 11 -12 are then the "Preface" with the initial "Welcome" that it would be much nicer to have straight after the cover. My suggestion would be:

old  |what | new
--- | --- | ---
1-2 | junk | Delete
3-8 | contents | 5-10
9 | citation | 4
10 | cover | 1
11-12  | preface | 2-3

Given that the contents are auto-placed at the start after the auto-title pages, that's the sort of stuff that would be much easier to do with `pdftk` than trying to internally wrangle it into that form.

**Comment by maelle** [comment]
but with such wrangling, the TOC will be all wrong so I'll explore other ways to get a better PDF. :thinking:

**Comment by maelle** [comment]
Another issue I see with using pdfk (well I'd be using the qpdf package) is that I'd need to hardcode the page numbers which is bound to break as the TOC length increases.

The most promising thing I saw is the option 

> The global R option bookdown.post.latex can be set to a function to post-process the LaTeX output. This function takes the character vector of the LaTeX output as its input argument, and should return a character vector to be written to the ‘.tex’ output file. This gives you full power to post-process the LaTeX output.

**Comment by maelle** [comment]
I'll hold off fixing this. I still hope there'll be some solution involving no LaTeX (maybe a bookdown format based on padgedjs).

**Comment by maelle** [comment]
I see there's `pagedown::book_crc()`.

**Comment by mpadge** [comment]
Yes, indeed, the ToC wasn't something I'd considered, yet must be

**Comment by mpadge** [comment]
This actually seems to have been automagically resolved in the intervening time. Book still starts with 2 initial pages, but first  is now simply a poorly-formatting title page, second is blank, then 3rd is ToC, and is should be. It's definitely not worth trying to reformat the initial title page, so I'm going to close this now.
