### ISSUE TITLE
Document finalize transfer command when ready

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#355]

**Comment by maelle** [comment]
@xuanxu Could buffy somehow watch the repo until it is transferred, to give the author admin rights again once a repo is transferred?

**Comment by maelle** [comment]
(related to the approval responder)

**Comment by xuanxu** [comment]
> @xuanxu Could buffy somehow watch the repo until it is transferred, to give the author admin rights again once a repo is transferred?

Currently this is not posible. We would need to listen to transfer-repo events and have it somehow associated with the review issue and package authors. Maybe the simplest way to achive this is to have a specific command to use when the package have been already transferred.

**Comment by maelle** [comment]
Oh that's a nice workaround, thank you! I opened https://github.com/ropensci-org/buffy/issues/39

**Comment by maelle** [comment]
Now related to https://github.com/ropensci-org/buffy/issues/52

**Comment by mpadge** [comment]
@maelle Just  noting that I the assignee of most issues for upcoming release, but this one really is your. Are you going to be able to address this prior to end of this week (13 May 2022)?

**Comment by maelle** [comment]
So, actually I'm not sure we need to document this, because the command is in the approval template. Is it enough "docs"? I'm worried that if we add text about this in the text of the dev guide, it could get out of sync.

**Comment by mpadge** [comment]
Yep, i definitely think that is enough then. Happy for you to just close this issue. Thanks

**Comment by maelle** [comment]
Thank _you_!
