### ISSUE TITLE
Update editor guide with add + assign bot commands 

### ISSUE THREAD

**Issue by mpadge** [ropensci/dev_guide#359]
https://github.com/ropensci-org/buffy/pull/42

@maelle I'm happy to do this - feel free to assign me

**Comment by maelle** [comment]
Cool, thank you, I've assigned the issue to you :grinning:

**Comment by mpadge** [comment]
sorry, that was on my todo list for this morning ... guess you bet me to it. Thanks

**Comment by maelle** [comment]
no problem!! I was working on the release preparation.
