### ISSUE TITLE
Collect more examples of reviews for editors

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#363]
With some words explaining why the example can be useful.
Could be used to have a few examples of "tough but constructive" reviews for instance.
The list would clearly state it's not exhaustive.

**Comment by noamross** [comment]
One good tough-but-constructive example: the part of this review suggesting a re-write of the vignette: https://github.com/ropensci/software-review/issues/191#issuecomment-368254623

**Comment by mpadge** [comment]
Another good example is for [the `slopes` package](https://github.com/ropensci/software-review/issues/420), which ended up being fundamentally redesigned in response to the reviews. All reviews/reviewers were at all times entirely constructive, which seems to have played a major role in motivating the authors to embark on such a major overhaul. Comments such as, "this package does not ..." or "has not ..." were invariably followed by constructive suggestions for what could be done (there are, for example, [several in one of the first reviews](https://github.com/ropensci/software-review/issues/420#issuecomment-858231647)).
