### ISSUE TITLE
Promote the book

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#38]
# When?

When it looks like the website? Cf #1  Or even before?
What about the progress of the contents before actively promoting?

# How

* Blog post /tech note with a few highlights (saying where to find the old content, explaining the structure logic, indicating how to contribute, mentioning things that can apply to any R package developer e.g. Scott's chapter about package evolution).

* Tweets spread out in time with "gems" "from our gitbook about package development"?

cc @stefaniebutland

**Comment by stefaniebutland** [comment]
We should discuss this in an upcoming staff meeting

**Comment by noamross** [comment]
I actually think we may want to do more soft-launch and feedback before posting about the book.  I say that we make a point to mention it in every response for authors and reviewers (even experienced ones, e.g., "We have updated and consolidated our guidelines [here], we suggest you peruse these."), as well as maybe ping the Slack to ask people to take a look.

**Comment by maelle** [comment]
Great point. We're actually more or less already doing it with links in blog posts and such but a more active approach is a good idea cf #41

**Comment by maelle** [comment]
When we have a cover for the book #34 we can submit it to bookdown.org https://bookdown.org/home/about/

**Comment by maelle** [comment]
https://github.com/rstudio/bookdown.org/pull/31
