### ISSUE TITLE
Acknowledgement of authorship / contributors

### ISSUE THREAD

**Issue by KlausVigo** [ropensci/dev_guide#388]
Hello all, 

I am not sure if this is the right place for this request. I observed now several times during review for MEE and recently rOpenSci that functions or code has been copied without proper acknowledgement. There are of course two simple solutions either import the function (which also avoids code duplication) or adding the authors of the function as contributors (see below). I myself contacted several times authors to add a function in one of my packages and always had positive feedback. This would allow the authors of such a contribution to claim these as a "broader impact" with funding authorities, etc.
 
This situation could be avoided if there would be a statement in the devguide similar to one of the first paragraphs of the [CRAN Repository Policy](https://cran.r-project.org/web/packages/policies.html):

"The ownership of copyright and intellectual property rights of all components of the package must be clear and unambiguous (including from the authors specification in the DESCRIPTION file). Where code is copied (or derived) from the work of others (including from R itself), care must be taken that any copyright/license statements are preserved and authorship is not misrepresented.

Preferably, an ‘Authors@R’ field would be used with ‘ctb’ roles for the authors of such code. Alternatively, the ‘Author’ field should list these authors as contributors.

Where copyrights are held by an entity other than the package authors, this should preferably be indicated via ‘cph’ roles in the ‘Authors@R’ field, or using a ‘Copyright’ field (if necessary referring to an inst/COPYRIGHTS file).

Trademarks must be respected."

Kind regards, 
Klaus

**Comment by mpadge** [comment]
@KlausVigo: @maelle and I have discussed this, and agree that this is a very important point to explicitly state in the DevGuide. Would you like to submit a PR adding your suggestions? It is also important to mention the potential for license conflicts, such as those raised by @assignUser, and to make a statement that authors should/must ensure that all potential or actual conflicts have been satisfactorily resolved through explicit and sufficiently detailed acknowledgements and modifications to DESC files. Thanks!

**Comment by maelle** [comment]
Just noting that PRs are best made against the dev branch. Thanks in any case for the issue!
