### ISSUE TITLE
Encourage structured release notes

### ISSUE THREAD

**Issue by sckott** [ropensci/dev_guide#40]
e.g., https://github.com/ropensci/lingtypology/blob/master/NEWS 

I would personally want everyone to break their release notes into sections so readers can quickly see, “oh, theres bug fixes”, or “oh, a new function”, etc. rather than having to sift through everything to get to sections of news they’re interested in 

Thoughts?  Can we add to our guide that we want users to break news into sections?

**Comment by sckott** [comment]
- rpkgs book has a small section on news files here http://r-pkgs.had.co.nz/release.html#news.md - suggests just a simple list of changes, then break them up into sections just before the release (or not if it's a small list )
- writing R extensions page points to https://www.gnu.org/prep/standards/standards.html#NEWS-File - which doesn't say anything about sections of a news file, though goes on much longer about changelog

**Comment by sckott** [comment]
- an example: https://github.com/ropensci/taxize/blob/master/NEWS.md
- a possible dictionary of headings:
    * New Features
    * Minor Improvements
    * Bug Fixes
    * Defunct & Deprecated
    * Documentation Fixes
    * (a special: any heading grouping a large number of changes under one thing)

**Comment by maelle** [comment]
The guide could mention https://github.com/krlmlr/fledge

**Comment by maelle** [comment]
Actually we already have nearly all this guidance and the current template https://ropensci.github.io/dev_guide/newstemplate.html has the sections. Will however update with new elements mentioned in this thread.
