### ISSUE TITLE
Align version number in DESCRIPTION with actual version

### ISSUE THREAD

**Issue by mpadge** [ropensci/dev_guide#443]
@maelle? The DESC version is not currently used, but should be, right? Would it be okay if I incremented it in current dev to 0.8.0?

**Comment by maelle** [comment]
yes good catch!

**Comment by maelle** [comment]
maybe it could be an item in the checklist

**Comment by mpadge** [comment]
It will be. I'm about to push the script for #442, and then I'll actually run it.
