### ISSUE TITLE
Move scripts to {devguider}

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#445]
Place-holder at https://github.com/ropensci-org/devguider/

**Comment by mpadge** [comment]
- [ ] Modify line added in #452

**Comment by mpadge** [comment]
Oh whoops, i missed that the milestone here was 0.9.0 - i've already moved them across, and we can do it as part of this release. Hope that's okay :grin:

**Comment by maelle** [comment]
it is, of course! :smile_cat:

**Comment by maelle** [comment]
@mpadge I think this can be closed now? Thanks for creating {devguider}!
