### ISSUE TITLE
travis.com vs travis.org

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#45]
The builds pass on travis.org but I receive build fail emails from travis.com -- how will Travis transfer affect deployments created with `tic` setup @krlmlr?

**Comment by krlmlr** [comment]
I haven't thought about this problem. Do we need to use a different API endpoint? I hope things will continue to run transparently, so that we can ignore this problem for a little while.

**Comment by krlmlr** [comment]
Added an issue to the _travis_ GitHub repo, looks like this needs some active investigation beforehand.

**Comment by maelle** [comment]
Cool thanks, I hope it won't be too hard!

**Comment by maelle** [comment]
related issue https://github.com/ropenscilabs/travis/issues/77

**Comment by maelle** [comment]
switching to GH actions anyway
