### ISSUE TITLE
Adding Privacy Banner

### ISSUE THREAD

**Issue by ClaudioZandonella** [ropensci/dev_guide#453]
Sorry for opening an issue not directly related to the book content, but I would be really interested in understanding how you added the privacy banner for using Matomo analytics.

I am trying to implement a privacy banner in one of my bookdown project but I could not find any documentation anywhere. Your book is the only bookdown I have ever seen with a privacy banner. Do you mind to offer some more insight into this?

Thank for any info you can provide.

**Comment by maelle** [comment]
:wave: @ClaudioZandonella! 

Do you use Matomo Analytics too? 

The technical pieces are https://github.com/ropensci/dev_guide/blob/3ec30926342d9235b90a282cd210ee3423af1068/_output.yml#L7-L8 (you could add any HTML via this YAML field) and https://github.com/ropensci/dev_guide/blob/master/matomo.html (we host the JS at our main website, but we got it via our Matomo dashboard).

I hope this helps!
