### ISSUE TITLE
Add advice on user agents?

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#474]
Specific to packages wrapping APIs.

Adding an user agent.
Should that user agent be different for package developers themselves and for CI.

**Comment by mpadge** [comment]
> Adding an user agent. Should that user agent be different for package developers themselves and for CI.

This is all very much "in flux". I think use of http2 in particular should translate to a general principle of using the same credentials/agents for CI, but also ensuring everything is redacted via httptest2. For other http systems recommendations would differ. So there seems to currently be a strong dependence of recommendations on http systems, but if we presume a general transition towards http2, then we can also presume a direction of future evolution of our recommendations in this regard.

**Comment by maelle** [comment]
Thanks! But user agents aren't really confidential info? 

- the package should provide a default user agent
- the package should let users override it (?)
- the package might change the user agent based on context (CI, package developers)

Why would that be different when using, say, curl?

**Comment by maelle** [comment]
https://github.com/EMODnet/EMODnetWFS/pull/125
