### ISSUE TITLE
“field and laboratory reproducibility tools” not in submission template

### ISSUE THREAD

**Issue by noamross** [ropensci/dev_guide#480]
The “field and laboratory reproducibility tools” category does not appear as an option in package submission, for instance, for packages like https://github.com/ropensci/software-review/issues/539

**Comment by maelle** [comment]
it's actually in the template https://github.com/ropensci/software-review/blob/master/.github/ISSUE_TEMPLATE/A-submit-software-for-review.md :thinking:

**Comment by maelle** [comment]
ah no the _Pre_ submission one lacks it indeed
