### ISSUE TITLE
Highlighting review values in more places

### ISSUE THREAD

**Issue by noamross** [ropensci/dev_guide#481]
As not everyone reads the full dev guide and other materials assigned before diving into review, it would be useful to better highlight some of our key values in a few more places to make sure to set the tone for review.   I think a brief statement of the type of interaction we expect from reviewers could be included in: 

 - The ***top*** of our guide for reviewers, with a header to emphasize it
 - Reviewer invitation email template
 - ropensci-review-bot response when a reviewer is assigned.

For the latter, two, this should be very succinct, so it can be included in brief messages as text, not a link.  A quick draft:

> rOpenSci’s community is our best asset. We aim for reviews to be open, non-adversarial, and focused on improving software quality. Be respectful and kind! See our [reviewers guide]() and [code of conduct]() for more.

**Comment by maelle** [comment]
:robot:  https://github.com/ropensci-org/buffy/pull/77
