### ISSUE TITLE
Clarify/add guidance on which team member to ask for help

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#483]
https://discuss.ropensci.org/t/staff-admin-team-codecov/2982

**Comment by maelle** [comment]
Should such guidance live in a new, last section of the authors guide? :thinking: 

Thoughts @mpadge?

**Comment by mpadge** [comment]
I agree with the suggestions of @ewallace that pinging @ropensci/staff or the likes would be a good idea, and that definitely should be listed somewhere. Or maybe even @ropensci/help might be more useful, and it would enable us (internal staff folk) to switch roles and always ensure a minimal crew is there to respond, without overburdening the rest.

**Comment by maelle** [comment]
we now have `@ropensci/admin`, I'll have to document this.

**Comment by maelle** [comment]
Maybe in a "now your package is in rOpenSci suite" cheatsheet

**Comment by maelle** [comment]
And in the "GitHub Grooming" chapter.
