### ISSUE TITLE
Instructions for reviews on non-default branch of repo

### ISSUE THREAD

**Issue by mpadge** [ropensci/dev_guide#485]
Idea from @s3alfisc, implemented in https://github.com/ropensci-review-tools/roreviewapi/issues/27. The ability to do this needs to be documented in Dev Guide. Alex: We encourage community contributions at every opportunity possible. Let us know if you'd like to submit the PR describing this ability. I'd suggest best place would be another dot-point in this list:
https://github.com/ropensci/dev_guide/blob/aff4bcdd9326c09fa9044088ef323998a08c8adc/softwarereview_author.Rmd#L31-L40
which ends up in rendered form [here](https://devguide.ropensci.org/authors-guide.html#the-submission-process).

**Comment by s3alfisc** [comment]
I will prepare a PR this evening!

**Comment by maelle** [comment]
Thanks @s3alfisc!

We'll also need to update the reviewer guide (installation instructions, a note to search the repo locally and not on GitHub as search is limited to the default branch).

**Comment by maelle** [comment]
Friendly reminder @s3alfisc :smile_cat:

**Comment by maelle** [comment]
(no worries if you don't have time!)
