### ISSUE TITLE
consistent link for rOpenSci’s suite of packages

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/dev_guide#52]
In https://ropensci.github.io/dev_guide/onboardingintro.html, "rOpenSci’s suite of packages" links to  our website https://ropensci.org/packages/, whereas elsewhere (can't recall), packages links to our GitHub https://github.com/ropensci.

**Comment by maelle** [comment]
Replacing two links right now, not sure I found all, so please re-open if you see the problem again, thanks!
