### ISSUE TITLE
no rejections for onboarding?

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/dev_guide#55]
Consider modifying the "rejection" language in https://ropensci.github.io/dev_guide/policies.html#package-submission since Karthik's slide says "no rejections" http://inundata.org/talks/ropensci_intro/#/0/12

**Comment by maelle** [comment]
I used the text of this slide too (3 times now 😹 ) and mentioned I'd explain out-of-scope rejections later in my talk. Maybe we should rather stop using that slide given it can be misinterpreted out-of-context (I have https://www.tidyverse.org/articles/2018/07/carpe-talk/ in mind).

**Comment by maelle** [comment]
cc @karthik

**Comment by maelle** [comment]
Assigning this to @karthik to remember to ask him his opinion. 😸

**Comment by karthik** [comment]
When I give talks I explicitly say that once we determine that a package is in scope, it does not get rejected after the review process has started. Package is improved from feedback or placed on hold until it reaches a satisfactory stage. "No rejections" taken out of context would definitely be wrong (as would be other things on various slide decks taken without context.)
