### ISSUE TITLE
add author response example in Spanish

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#583]
when there are more examples

cc @yabellini

**Comment by oraliahdz** [comment]
Hi, is this still Open? I can help with the translation. What is the original version?

**Comment by yabellini** [comment]
@oraliahdz, thank you so much for your offer. We are talking about examples of comments on our peer review process issues in Spanish. 

But we will have some material to translate into Spanish soon. I will ping you when we have everything ready for that task, and then you can check if you can and want to participate.

**Comment by oraliahdz** [comment]
Sure
