### ISSUE TITLE
Edit repo action takes you to a 404 page. 

### ISSUE THREAD

**Issue by eliocamp** [ropensci/dev_guide#591]
Clicking on the "Edit this page" button takes you to a non-existing page. I think the issue is that the URL uses the `master` branch (i.e. https://github.com/ropensci/dev_guide/edit/*master*/maintenance_curation.Rmd) instead of main (i.e. https://github.com/ropensci/dev_guide/edit/*main*/maintenance_curation.Rmd).

**Comment by maelle** [comment]
@eliocamp you mean from devguide.ropensci.org? I think it's fixed for the dev dev guide https://devdevguide.netlify.app/

**Comment by maelle** [comment]
Thanks for the report in any case, always appreciated! :pray:

**Comment by eliocamp** [comment]
Ah, yes. Then it's fixed. :)
