### ISSUE TITLE
semantics Q about 14.4 Finding where to contribute code or documentation

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/dev_guide#61]
In https://ropensci.github.io/dev_guide/contributingguide.html#finding-where-to-contribute-code-or-documentation, section starts with "Most of our packages are developed on GitHub. We have two organizations:..."

Do we have any  that are not developed on GitHub? Clarify or reword

**Comment by maelle** [comment]
Ah true, even `gitlabr` (submitted but not onboarded, submission stalled) is/was developed on GitHub.
