### ISSUE TITLE
add link to 14.4 Finding where to contribute

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/dev_guide#62]
in "Tell us about your expertise and interests..." in Stef's update of https://ropensci.github.io/dev_guide/contributingguide.html#finding-where-to-contribute-code-or-documentation

where do we want people to do this so we can match them with a package to contribute to? Discussion forum probably best, but which category? Once decided, consider updating that category description to match the guide text

**Comment by maelle** [comment]
@sckott, which category of the forum would make sense? Assigning you because you know more about the forum 😉

**Comment by sckott** [comment]
It could be possibly https://discuss.ropensci.org/c/questions or https://discuss.ropensci.org/c/community or we could make a new one if those don't seem to fit

**Comment by stefaniebutland** [comment]
I'll have a think about this in my next round of reviewing the Contributing Guide chapter soon

**Comment by maelle** [comment]
Any updated on a good forum category @stefaniebutland? Now (right before Hacktoberfest) might be a good time for creating it.

**Comment by maelle** [comment]
Should the forum gain a "contributing" category where people could post their wish to get involved? @sckott

**Comment by sckott** [comment]
@maelle good idea. thoughts @stefaniebutland

**Comment by sckott** [comment]
i'm pretty sure it's pinned, when I go to settigns on the right, it asks if I want to unpin it 
<img width="231" alt="screen shot 2018-12-04 at 2 59 33 pm" src="https://user-images.githubusercontent.com/577668/49478662-3f7c3700-f7d5-11e8-8873-1c2e98e7faf4.png">
