### ISSUE TITLE
change Use Cases forum description?

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/dev_guide#63]
In https://ropensci.github.io/dev_guide/contributingguide.html once we agree on text for how to report use cases, change Use Cases forum description to match guide text

**Comment by maelle** [comment]
@sckott I don't have admin rights to update the forum description, could you please do this?

The text in the book is now "please post the link to our [discussion forum in the Use Cases category](https://discuss.ropensci.org/c/usecases) and tag Scott Chamberlain (`@sckott`) for inclusion in the [rOpenSci biweekly newsletter](https://news.ropensci.org/)" and for authors I added they could report it by Slack (in order to lower the effort needed for them, but can change the wording again if you prefer!).

**Comment by sckott** [comment]
by forum description do you mean this https://discuss.ropensci.org/t/about-the-usecases-category/33 ?

**Comment by stefaniebutland** [comment]
Yes that one.

**Comment by stefaniebutland** [comment]
@sckott suggested text added to existing (too long? wanted to preserve your original txt).

UseCases is for discussion and [reporting of use cases](https://ropensci.github.io/dev_guide/contributingguide.html#reporting-use-cases).

This category isn’t linked to any particular piece of software, but is more about real world problems you have, in which you think there could be some solution in the world of rOpenSci, or thereabouts anyway. 

If you see a use case of one of our packages "in the wild", please post the link here, tag @sckott for inclusion in the rOpenSci biweekly newsletter and tag the package author. It’s valuable to both users and developers of a package to see how it's been used.

**Comment by maelle** [comment]
With a link to the newsletter?

**Comment by stefaniebutland** [comment]
edited my comment to include link to newsletter

**Comment by maelle** [comment]
@sckott could you change https://discuss.ropensci.org/t/about-the-usecases-category/33
to the text suggested by @stefaniebutland in https://github.com/ropensci/dev_guide/issues/63#issuecomment-406395031 i.e.

> UseCases is for discussion and reporting of use cases.

> This category isn’t linked to any particular piece of software, but is more about real world problems you have, in which you think there could be some solution in the world of rOpenSci, or thereabouts anyway.

> If you see a use case of one of our packages "in the wild", please post the link here, tag @sckott for inclusion in the rOpenSci biweekly newsletter and tag the package author. It’s valuable to both users and developers of a package to see how it's been used.

**Comment by sckott** [comment]
done ✔️

**Comment by maelle** [comment]
Yay thanks!
