### ISSUE TITLE
Add doi Zenodo links for the Spanish version

### ISSUE THREAD

**Issue by paocorrales** [ropensci/dev_guide#634]
When the Spanish version is ready. Also the link to the pdf version

**Comment by yabellini** [comment]
My recommendation about citation, base in previews experiences:

The cite of the translation change for every language. We base this recommendations on the [APA recommendations article, Section Book, republished in translation](https://apastyle.apa.org/blog/citing-translated-works). We also recommend including the original title in English, [following this APA suggestion](https://writeanswers.royalroads.ca/faq/199295). See example for Piaget (1950).

The general format is:

{list of authors of the English version}.{(year of publication)}. {Translated title}. {[Original Title in English]} (Translation to {language name}: {list of people that translate the material}). {DOI}. (Original work publish at {year of publication})

The text Translation to and Original work publish at should be writing on the language of the translations.

Example using the developer guide:

    rOpenSci, Anderson, Brooke, Chamberlain, Scott, DeCicco, Laura, Gustavsen, Julia, Krystalli, Anna, Lepore, Mauro, Mullen, Lincoln, Ram, Karthik, Ross, Noam, Salmon, Maëlle, Vidoni, Melina, Riederer, Emily, Sparks, Adam, & Hollister, Jeff. (2021). Paquetes rOpenSci: Desarrollo, mantenimiento y revisión por pares [rOpenSci Packages: Development, Maintenance, and Peer Review] (Traducción al español: {name of the translators}) Zenodo. https://doi.org/10.5281/zenodo.6619350 (Trabajo original publicado en 2021)

**Comment by maelle** [comment]
so no new Zenodo DOI? Could you please make a PR to index.es.Rmd? Thanks

**Comment by paocorrales** [comment]
We should also need a Zenodo DOI, we talked al little about this with Yani last Tuesday. I'm going to check if Zedodo can handle translations or if we need to create an independent DOI.

**Comment by paocorrales** [comment]
I don't see anything related to the translation of materials on the Zenodo web page. We could al least add the DOI of the English version to the metadata to "link" both versions.

**Comment by maelle** [comment]
@mpadge what would you advise us to do for the next release?

**Comment by mpadge** [comment]
I'd suggest doing an entirely separate Zenodo release for the spanish version. You'd then have 2 distinct primary DOIs, and updates would be automatically handled for each of those.

**Comment by maelle** [comment]
The trouble is, at the moment the Zenodo releases are automatic, they correspond to releases of the GitHub repository. So should I unset that, and instead submit two PDFs to Zenodo separately? :thinking:

**Comment by mpadge** [comment]
Oh right ... that is a problem. https://developers.zenodo.org/#new-version - there really can be only one published version at a time on Zenodo. One approach might be to update our release workflow to release two versions:

- First the Spanish one, with a version set in [`.zenodo.json`](https://github.com/ropensci/dev_guide/blob/main/.zenodo.json) to something like `version: "0.X.Y-sp"`. Release that, then,
- Release the default English version with `version: "0.x.Y"`

DOI would always resolve to default English version, but Spanish version would always be able to be obtained as the release prior to latest. Hacky, but it should work?

**Comment by maelle** [comment]
What about I keep the current workflow for the English version.

For the Spanish one, I upload a PDF to Zenodo. @yabellini do you know of examples of Zenodo things that are actually translations, not originals?

Then I'd put the Zenodo DOI in the Spanish version, and edit the GitHub release. All of this to ensure devguide dot ropensci dot org has the right stuff.

**Comment by maelle** [comment]
I'd probably actually first upload a PDF to Zenodo, then add this link to the Spanish index, then do the release.
