### ISSUE TITLE
add txt on benefits of contributing?

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/dev_guide#64]
In https://ropensci.github.io/dev_guide/contributingguide.html should we add text to say what the benefits of contributing are - learning, improve your own code, more public face for your work?? See Kara Woo’s CascadiaR talk slides for analogy re: play with a puppy and give it back ;-)

**Comment by maelle** [comment]
I added very brief text only, is this enough?

I wasn't able to add the great puppy analogy of @karawoo's because it wasn't written in the slides so I was afraid to 1) infringe copyright 2) not remember it well enough.

**Comment by stefaniebutland** [comment]
I'll edit a bit, but not rn

**Comment by maelle** [comment]
@stefaniebutland do we want to right some text about why rOpenSci is a good place to contribute? Rather than why contribute in itself? Maybe just a few sentences about our mission + rOpenSci being a friendly place?

**Comment by maelle** [comment]
@stefaniebutland do you think you could help with this? If so, before May the 16th or after that? (so I can assess in which version this edit would go :-) )

**Comment by stefaniebutland** [comment]
My suggested edits in google doc shared with Maëlle.
