### ISSUE TITLE
Keep suggesting PRs?

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#65]
Now in https://ropensci.github.io/dev_guide/contributingguide.html#reporting-use-cases @stefaniebutland added "Let the package author know by opening an issue in the GitHub repository for that package, perhaps suggesting they create a “use cases in the wild” section in the README, and maybe even tag them in a tweet about the use case. This goes a long way to encouraging people to keep up development knowing there are others who appreciate and build on their work."

but since the README section is only a suggestion I now wonder if this could lead to awkward situations? Should we only mention telling rOpenSci about the use case? But doing the dispatch ourselves would mean more work. 🤔

**Comment by maelle** [comment]
What I mean is that I am afraid some authors won't want such a section? Hopefully not.

Very fewrepos have that at the moment.

**Comment by stefaniebutland** [comment]
>  I am afraid some authors won't want such a section

I think this is a good reason not to recommend PR, but to open an issue suggesting it. Less "aggressive".

**Comment by maelle** [comment]
Ok can you make a PR? 🙂

**Comment by maelle** [comment]
Or wait it is already the current phrasing right? :woman_facepalming:

**Comment by stefaniebutland** [comment]
I think current phrasing is good as is.
