### ISSUE TITLE
lifecycle badge maturing is being phased out

### ISSUE THREAD

**Issue by bart1** [ropensci/dev_guide#661]
The guide for authors: https://devguide.ropensci.org/authors-guide.html currently refers to the lifecycle badge `maturing`. As this is currently not included in lifecycle anymore: https://lifecycle.r-lib.org/articles/stages.html#maturing it might be good to look for an alternative. However there seems to be nothing between `experimental` and `stable` so I'm unsure what the fix would be.

**Comment by mpadge** [comment]
Thanks @bart1. It'd be great if you could PR corresponding changes. I'd say simply replacing "maturing" with "stable" would be best, so
> when the package is ~~at least Maturing~~ stable.

Thanks!
