### ISSUE TITLE
Bioconductor guidelines

### ISSUE THREAD

**Issue by llrs** [ropensci/dev_guide#663]
In the [first chapter](https://devguide.ropensci.org/building.html#bioconductor-gotchas) there is a Bioconductor gotcha section pointing to the official page. They are replicating the website in a book (following the rOpenSci example) and new changes are added to [that book](https://contributions.bioconductor.org/).

Maybe it would be better for people to add a link to the book too.

**Comment by maelle** [comment]
Oh, excellent point, thank you! Would you have time to make a PR?
