### ISSUE TITLE
doubt on meaning of a particular sentence

### ISSUE THREAD

**Issue by pedropark99** [ropensci/dev_guide#670]
Hey! My name is Pedro. Following the objectives of project [Multilingual Publishing](https://ropensci.org/multilingual-publishing/), I'm trying to translate the dev guide to portuguese. However, I am looking to a particular statement on section [Book release guidance](https://devguide.ropensci.org/bookreleaseissue.html#bookreleaseissue) of the guide, and I'm not sure if I got the meaning right.

> Editors preparing for a release can run the prelease.R script in the inst directory of this repository to automatically open a GitHub issue with checkpoints for all current issues assigned to the upcoming release milestone, along with the following checklist. Before running the script, please manually check the assignment of issues to the milestone. This should be run one month prior to planned release.

My problem is on the statement "Before running the script, please manually check the assignment of issues to the milestone."

Did you mean: "Before publishing your version of the book, you should check if your version of the book fits into the next milestone of the book. In other words, is your version of the book in accordance to the objects that the editors and project managers assigned to the next milestone of the project."  ?

Is that right ? Am I interpreting it correctly ?

Have a good day!

**Comment by yabellini** [comment]
Olá @pedropark99 :-) 

Thank you very much for your enthusiasm in doing the Portuguese translation. 

To do translations, we have a series of packages and a process to follow that make the whole activity easier.  We are working on this Translation Guidelines here: https://translationguide.ropensci.org/ (it is a work in process but would be nice to have your feedback on the instructions).

We create this packages and this process, so the translations are sustainable and kept up to date. Would you mind writing me here: yabellini@ropensci.org, so we can chat and see how we can support you on this effort? 

Muito obrigada!

**Comment by pedropark99** [comment]
Of course! I send you an email. Thank you very much. Um prazer 😉

**Comment by pedropark99** [comment]
Close issue
