### ISSUE TITLE
Setting editor availability status

### ISSUE THREAD

**Issue by noamross** [ropensci/dev_guide#683]
It would be good to have a mechanism for editors to flag vacation/busy/available status so that (a) reviewers and authors would be aware of it so as to expect a slower response, and (b) EiCs could use it to determine whether to assign something.  Outside of vacation, we would have defined expectations (e.g., ~2 business day response), and for extended (>2 week) periods we could have another policy to make sure someone steps in to take over review threads if needed.

GitHub status (https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile#setting-a-status) might be one way to do this.

Another would be Slack statuses

**Comment by noamross** [comment]
@ropensci/editors What do you think? What's the easiest way to indicate this? Mauro has made this nice automated repository that checks whether editors are active: https://github.com/maurolepore/editors . GitHub status would be the easiest way to add something like `ON VACATION`.

**Comment by maurolepore** [comment]
Thanks Noam, I like the idea. 
Also I like that the implementations you suggest are simple. 
It seems to me that Slack status would allow a more granular control. I can imagine taking a vacation from my paid work but not from my rOpeSci duties or the other way around.

**Comment by maelle** [comment]
@noamross should your recent experiments be documented here?

**Comment by mpadge** [comment]
@maelle This will all become part of the dashboard, which will include documentation of how, where, when. This issue can stay open until it's been addressed there. Thanks!

**Comment by mpadge** [comment]
This has now all been addressed in https://ropensci-review-tools.github.io/dashboard/editors.html, so closing now. Description of the dashboard in DevGuide will be done via #828
