### ISSUE TITLE
Clarify man-roxygen comment

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#72]
In https://ropensci.github.io/dev_guide/building.html#examples (file to edit = https://github.com/ropensci/dev_guide/blob/master/pkg_building.Rmd )

@sckott assigning this to you because I only know this strategy from packages of yours like https://github.com/ropensci/taxize/tree/master/man-roxygen Maybe add a sentence or two about how to do this, with a link to a package where you've done that? Thanks! 😸

**Comment by sckott** [comment]
will do

**Comment by maelle** [comment]
Thank you!

**Comment by sckott** [comment]
I'd say something like: 

> Put any documentation for an object in a `.R` file in the `man-roxygen` folder (at the root of your package). For example, this file https://github.com/ropensci/rgbif/blob/master/man-roxygen/occ_search_egs.R. Link to that template file from your function (e.g., https://github.com/ropensci/rgbif/blob/master/R/occ_search.r ) with the `@template` keyword (e.g., https://github.com/ropensci/rgbif/blob/master/R/occ_search.r#L7). The contents of the template will be inserted when documentation is built into the resulting `.Rd` file that users will see when they ask for documentation for the function. 

> Note that if you are using markdown documentation, markdown currently doesn't work in template files, so make sure to use latex formatting.

thoguhts @maelle ?

**Comment by maelle** [comment]
Thank you! Could you add a bit about _why_ one should do this?

Is the Markdown doc caveat still valid, if so, are there plans to solve it?

**Comment by sckott** [comment]
For why, maybe this, but feel free to edit:

> In most cases you can ignore templates and `man-roxygen`, but there are two cases in which leveraging them will greatly help: 

> 1. When you have a lot of documentation for a function/class/object separating out certain chunks of that documentation can keep your `.R` source file tidy. This is especially useful when you have a lot of code in that `.R` file.
> 2. When you have the same documentation parts used across many `.R` functions it's helpful to use a template. This reduces deplicated text, and helps prevent mistakingly updating documentation for one function but not the other.

Yes, markdown still doesn't work AFAIK.
