### ISSUE TITLE
CONTRIBUTING.md and translation

### ISSUE THREAD

**Issue by noamross** [ropensci/dev_guide#784]
- I suggest we move info in the README on contributing to a CONTRIBUTING.md file so it appears when creating a pull request
- I also would suggest some info on translation workflow and expectations and links to relevant documentation.  I had a small patch (#783), and had to dig around to find:
    - https://ropensci.org/blog/2023/09/26/how-to-translate-a-hugo-blog-post-with-babeldown/
    - https://translationguide.ropensci.org/howtoreview.html
- I don't believe any of this has guidance yet for what to do for PRs that are small changes to text within a larger body - should one update only that section or the while file?

**Comment by maelle** [comment]
Thanks for opening this issue! I plan to first write a tech note about the new babeldown function, then to update the guidance. (the function is still very new)

**Comment by maelle** [comment]
I'll add something next week or later.
