### ISSUE TITLE
How to handle Portuguese in-progress translation in the next release

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#800]
@yabellini @mpadge  I want to release the dev guide one month from now. The Portuguese version won't be finished by now I guess. 

Therefore, what makes more sense

- release as is, with some chapters translated to Portuguese, others actually placeholders in English.
- completely remove Portuguese from the release (so devguide.ropensci.org would have Spanish and English; devdevguide.netlify.app would have all three languages)

Thoughts?

I don't want to delay the release any further because it's been delayed a lot already. :sweat_smile:

**Comment by mpadge** [comment]
My suggestion would be the second option - I doubt there'd me much gain from only partial Portuguese, and definitely risk of confusion.

**Comment by yabellini** [comment]
I think the best is to remove Portuguese from this release.

**Comment by yabellini** [comment]
I love when we agree :-)

**Comment by maelle** [comment]
Good, that's what I will do then!
