### ISSUE TITLE
Broken Linksoftwarereview_reviewer.Rmd

### ISSUE THREAD

**Issue by LizHareDogs** [ropensci/dev_guide#842]
Hi! This guide is so helpful as I get ready to do my first review. Thanks rOpenSci folks.

I noticed a broken link in softwarereview_reviewer.Rmd on  line 85, which is Adam Sparks'  Twitter/X post. 

X says "...this page doesn’t exist. Try searching for something else"

I guess the reference should be removed?

**Comment by maelle** [comment]
Thanks so much! I opened #843
