### ISSUE TITLE
Add a link to the tidyverse NEWS style guide

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#87]
http://style.tidyverse.org/news.html

**Comment by maelle** [comment]
@ropensci/editors should we recommend/suggest the tidyverse NEWS style guide?

**Comment by lmullen** [comment]
It's a little overly prescriptive but as a recommendation, sure, I'm fine with that.

**Comment by noamross** [comment]
Agree I'd go with "we suggest" as language.
