### ISSUE TITLE
add pkgreviewr to reviewer guidance

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#9]
poke @annakrystalli (see it's on my TODO list now 🎊 )

**Comment by maelle** [comment]
@annakrystalli would you be able to PR a few lines about that?

**Comment by annakrystalli** [comment]
Sure. I've actually been working on it. There's currently an issue with `git2r::clone()` so I've been trying to put in a temporary work around. When I update the package I will!

**Comment by maelle** [comment]
Thanks! Happy to help test the package btw.
