### ISSUE TITLE
Add some guidance on how and why to limit dependencies

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#91]
No requirements, just giving food for thought.

Under https://ropensci.github.io/dev_guide/building.html#package-dependencies

Related to #90

**Comment by sckott** [comment]
how does this look @maelle https://github.com/ropensci/dev_guide/commit/737876c363be59f2298ccf0f20fc5d1d3ab85357 ?

**Comment by maelle** [comment]
Nice. Don't hesitate to add a link to your blog post as well!

**Comment by maelle** [comment]
I also wonder how to add something about not having two dependencies overlapping in functionality, e.g. don't depend on `dplyr` _and_ `data.table` when you can pick one? 🤔

**Comment by sckott** [comment]
added a note about overlapping
