### ISSUE TITLE
Add crul as a possibility in "Recommended scaffolding"

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#92]
I.e. "For http requests we strongly recommend using httr over RCurl."

"For http requests we strongly recommend using httr (and testing with httptest) or crul (and testing with vcr and webmockr) over RCurl."

The strong recommendation might become a requirement, I think we don't want any package to depend on RCurl?

**Comment by maelle** [comment]
Ok!

**Comment by sckott** [comment]
what do you think @maelle https://github.com/ropensci/dev_guide/commit/c3ef9361b0ec1609a926de25ba86df76ad6a53ad

**Comment by sckott** [comment]
I think `vcr` is the better option

**Comment by maelle** [comment]
without `webmockr`?

**Comment by sckott** [comment]
turns out you don't need to list `webmockr` if you're just using `vcr`
